package com.foundations.calculator.content;
import java.util.*;
import java.util.function.Supplier;
import com.foundations.calculator.FoundationsCalculator;
import com.foundations.calculator.core.*;
import com.foundations.calculator.menu.CalculatorMenu;
import com.mojang.serialization.Codec;
import net.minecraft.core.*;
import net.minecraft.core.component.*;
import net.minecraft.core.registries.*;
import net.minecraft.network.chat.Component;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.resources.*;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.*;
import net.minecraft.world.item.component.Unbreakable;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.*;
import net.minecraft.world.level.block.grower.TreeGrower;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.capabilities.*;
import net.neoforged.neoforge.common.extensions.IMenuTypeExtension;
import net.neoforged.neoforge.registries.*;

public final class Content {
    public static final DeferredRegister.Blocks BLOCKS=DeferredRegister.createBlocks(FoundationsCalculator.ID);
    public static final Supplier<Block> EXTENSION=BLOCKS.register("machine_extension",()->new MachineExtensionBlock(BlockBehaviour.Properties.of().strength(1,12).noOcclusion().noLootTable()));
    public static final DeferredRegister.Items ITEMS=DeferredRegister.createItems(FoundationsCalculator.ID);
    public static final DeferredRegister<BlockEntityType<?>> ENTITIES=DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE,FoundationsCalculator.ID);
    public static final DeferredRegister<net.minecraft.world.entity.EntityType<?>> PROJECTILES=DeferredRegister.create(Registries.ENTITY_TYPE,FoundationsCalculator.ID);
    public static final Supplier<net.minecraft.world.entity.EntityType<ThrownMaterialEntity>> SOIL_PROJECTILE=PROJECTILES.register("thrown_soil",()->net.minecraft.world.entity.EntityType.Builder.<ThrownMaterialEntity>of(ThrownMaterialEntity::new,net.minecraft.world.entity.MobCategory.MISC).sized(.25f,.25f).clientTrackingRange(4).updateInterval(10).build("foundations_calculator:thrown_soil"));
    public static final Supplier<net.minecraft.world.entity.EntityType<ThrownMaterialEntity>> STONE_PROJECTILE=PROJECTILES.register("thrown_stone",()->net.minecraft.world.entity.EntityType.Builder.<ThrownMaterialEntity>of(ThrownMaterialEntity::new,net.minecraft.world.entity.MobCategory.MISC).sized(.25f,.25f).clientTrackingRange(4).updateInterval(10).build("foundations_calculator:thrown_stone"));
    public static final Supplier<net.minecraft.world.entity.EntityType<GrenadeEntity>> GRENADE=PROJECTILES.register("grenade",()->net.minecraft.world.entity.EntityType.Builder.<GrenadeEntity>of(GrenadeEntity::new,net.minecraft.world.entity.MobCategory.MISC).sized(.25f,.25f).clientTrackingRange(4).updateInterval(10).build("foundations_calculator:grenade"));
    public static final Supplier<net.minecraft.world.entity.EntityType<GrenadeEntity>> BABY_GRENADE=PROJECTILES.register("baby_grenade",()->net.minecraft.world.entity.EntityType.Builder.<GrenadeEntity>of(GrenadeEntity::new,net.minecraft.world.entity.MobCategory.MISC).sized(.25f,.25f).clientTrackingRange(4).updateInterval(10).build("foundations_calculator:baby_grenade"));
    public static final DeferredRegister<MenuType<?>> MENUS=DeferredRegister.create(Registries.MENU,FoundationsCalculator.ID);
    public static final DeferredRegister<RecipeType<?>> TYPES=DeferredRegister.create(Registries.RECIPE_TYPE,FoundationsCalculator.ID);
    public static final DeferredRegister<RecipeSerializer<?>> SERIALIZERS=DeferredRegister.create(Registries.RECIPE_SERIALIZER,FoundationsCalculator.ID);
    public static final DeferredRegister<DataComponentType<?>> COMPONENTS=DeferredRegister.create(Registries.DATA_COMPONENT_TYPE,FoundationsCalculator.ID);
    public static final DeferredRegister<CreativeModeTab> TABS=DeferredRegister.create(Registries.CREATIVE_MODE_TAB,FoundationsCalculator.ID);
    public static final Map<String,Supplier<? extends Block>> BLOCKS_BY_ID=new LinkedHashMap<>();
    public static final Map<String,Supplier<? extends Item>> ITEMS_BY_ID=new LinkedHashMap<>();
    private static final List<Supplier<? extends Block>> MACHINE_BLOCKS=new ArrayList<>();
    public static final Set<String> PENDING=Set.of();
    public static final Supplier<DataComponentType<net.minecraft.world.item.component.ItemContainerContents>> MODULES=COMPONENTS.register("modules",()->DataComponentType.<net.minecraft.world.item.component.ItemContainerContents>builder().persistent(net.minecraft.world.item.component.ItemContainerContents.CODEC).networkSynchronized(net.minecraft.world.item.component.ItemContainerContents.STREAM_CODEC).build());
    public static final Supplier<DataComponentType<Integer>> ENERGY=COMPONENTS.register("energy",()->DataComponentType.<Integer>builder().persistent(Codec.intRange(0,Integer.MAX_VALUE)).networkSynchronized(ByteBufCodecs.VAR_INT).build());
    /** 0.0.2a long-valued energy. The legacy int component remains for migration/downgrade safety. */
    public static final Supplier<DataComponentType<Long>> ENERGY_LONG=COMPONENTS.register("energy_long",()->DataComponentType.<Long>builder().persistent(Codec.LONG).networkSynchronized(ByteBufCodecs.VAR_LONG).build());
    public static final Supplier<BlockEntityType<MachineBlockEntity>> MACHINE_ENTITY=ENTITIES.register("machine",()->BlockEntityType.Builder.of(MachineBlockEntity::new,MACHINE_BLOCKS.stream().map(Supplier::get).toArray(Block[]::new)).build(null));
    public static final Supplier<MenuType<com.foundations.calculator.menu.BulkStorageMenu>> BULK_MENU=MENUS.register("bulk_storage",()->IMenuTypeExtension.create(com.foundations.calculator.menu.BulkStorageMenu::fromNetwork));
    public static final Supplier<MenuType<com.foundations.calculator.menu.SmeltingModuleMenu>> SMELTING_MENU=MENUS.register("smelting_module",()->IMenuTypeExtension.create(com.foundations.calculator.menu.SmeltingModuleMenu::fromNetwork));
    public static final Supplier<MenuType<CalculatorMenu>> MENU=MENUS.register("calculator",()->IMenuTypeExtension.create(CalculatorMenu::fromNetwork));
    public static final Supplier<RecipeType<ProcessRecipe>> PROCESS_TYPE=TYPES.register("process",()->new RecipeType<>(){public String toString(){return "foundations_calculator:process";}});
    public static final Supplier<RecipeSerializer<ProcessRecipe>> PROCESS_SERIALIZER=SERIALIZERS.register("process",ProcessRecipe.Serializer::new);
    static {
        addBlock("research_chamber",()->new MachineBlock(ContentProperties.block("research_chamber",BlockBehaviour.Properties.of().strength(2,10).noOcclusion())),true,false);
        ITEMS_BY_ID.put("smelting_module",ITEMS.register("smelting_module",()->new CalculatorItem("smelting_module",50000,ContentProperties.item("smelting_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("atomic_terrain_module",ITEMS.register("atomic_terrain_module",()->new CalculatorItem("atomic_terrain_module",20000,ContentProperties.item("atomic_terrain_module",new Item.Properties().stacksTo(1)))));
        addBlock("flawless_glass",()->new ConnectedDecorBlock(ContentProperties.block("flawless_glass",BlockBehaviour.Properties.of().strength(0.6f,6f).lightLevel(s->9).noOcclusion().isViewBlocking((s,w,p)->false))),false,false);
        addBlock("purified_obsidian",()->new PurifiedObsidianBlock(ContentProperties.block("purified_obsidian",BlockBehaviour.Properties.of().strength(-1,3600000))),false,false);
        addBlock("power_cube",()->new MachineBlock(ContentProperties.block("power_cube",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("advanced_power_cube",()->new MachineBlock(ContentProperties.block("advanced_power_cube",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("creative_power_cube",()->new MachineBlock(ContentProperties.block("creative_power_cube",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("atomic_calculator",()->new MachineBlock(ContentProperties.block("atomic_calculator",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("dynamic_calculator",()->new MachineBlock(ContentProperties.block("dynamic_calculator",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("module_workstation",()->new MachineBlock(ContentProperties.block("module_workstation",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("reinforced_furnace",()->new MachineBlock(ContentProperties.block("reinforced_furnace",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("reinforced_chest",()->new MachineBlock(ContentProperties.block("reinforced_chest",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("stone_separator",()->new MachineBlock(ContentProperties.block("stone_separator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("algorithm_separator",()->new MachineBlock(ContentProperties.block("algorithm_separator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("hunger_processor",()->new MachineBlock(ContentProperties.block("hunger_processor",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("health_processor",()->new MachineBlock(ContentProperties.block("health_processor",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("amethyst_piping",()->new NutritionPipeBlock("amethyst_piping",ContentProperties.block("amethyst_piping",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),false,false);
        addBlock("tanzanite_piping",()->new NutritionPipeBlock("tanzanite_piping",ContentProperties.block("tanzanite_piping",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),false,false);
        addBlock("docking_station",()->new MachineBlock(ContentProperties.block("docking_station",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("atomic_multiplier",()->new MachineBlock(ContentProperties.block("atomic_multiplier",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("extraction_chamber",()->new MachineBlock(ContentProperties.block("extraction_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("restoration_chamber",()->new MachineBlock(ContentProperties.block("restoration_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("reassembly_chamber",()->new MachineBlock(ContentProperties.block("reassembly_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("precision_chamber",()->new MachineBlock(ContentProperties.block("precision_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("processing_chamber",()->new MachineBlock(ContentProperties.block("processing_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("analysing_chamber",()->new MachineBlock(ContentProperties.block("analysing_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("storage_chamber",()->new MachineBlock(ContentProperties.block("storage_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("fabrication_chamber",()->new MachineBlock(ContentProperties.block("fabrication_chamber",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("basic_greenhouse",()->new MachineBlock(ContentProperties.block("basic_greenhouse",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("advanced_greenhouse",()->new MachineBlock(ContentProperties.block("advanced_greenhouse",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("flawless_greenhouse",()->new MachineBlock(ContentProperties.block("flawless_greenhouse",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("co2_generator",()->new MachineBlock(ContentProperties.block("co2_generator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("calculator_locator",()->new MachineBlock(ContentProperties.block("calculator_locator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("calculator_plug",()->new MachineBlock(ContentProperties.block("calculator_plug",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("conductor_mast",()->new MachineBlock(ContentProperties.block("conductor_mast",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("weather_station",()->new MachineBlock(ContentProperties.block("weather_station",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("transmitter",()->new MachineBlock(ContentProperties.block("transmitter",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("starch_extractor",()->new MachineBlock(ContentProperties.block("starch_extractor",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("redstone_extractor",()->new MachineBlock(ContentProperties.block("redstone_extractor",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("glowstone_extractor",()->new MachineBlock(ContentProperties.block("glowstone_extractor",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("hand_cranked_generator",()->new MachineBlock(ContentProperties.block("hand_cranked_generator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("crank_handle",()->new MachineBlock(ContentProperties.block("crank_handle",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("magnetic_flux",()->new MachineBlock(ContentProperties.block("magnetic_flux",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion())),true,false);
        addBlock("weather_controller",()->new MachineBlock(ContentProperties.block("weather_controller",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("rain_sensor",()->new MachineBlock(ContentProperties.block("rain_sensor",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("stone_assimilator",()->new MachineBlock(ContentProperties.block("stone_assimilator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("algorithm_assimilator",()->new MachineBlock(ContentProperties.block("algorithm_assimilator",BlockBehaviour.Properties.of().strength(1.0f,12.0f).lightLevel(s->9).noOcclusion())),true,false);
        addBlock("gas_lantern_off",()->new MachineBlock(ContentProperties.block("gas_lantern_off",BlockBehaviour.Properties.of().strength(0.1f,6f).noOcclusion().lightLevel(s->s.getValue(MachineBlock.ACTIVE)?15:0))),true,false);
        addBlock("lantern",()->new LanternBlock(ContentProperties.block("lantern",BlockBehaviour.Properties.ofFullCopy(Blocks.LANTERN))),false,false);
        addBlock("scarecrow",()->new MachineBlock(ContentProperties.block("scarecrow",BlockBehaviour.Properties.of().strength(0.5f,14.399999999999999f).noOcclusion())),true,false);
        addBlock("amethyst_log",()->new RotatedPillarBlock(ContentProperties.block("amethyst_log",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG))),false,false);
        addBlock("amethyst_planks",()->new Block(ContentProperties.block("amethyst_planks",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("amethyst_stairs",()->new StairBlock(block("amethyst_planks").defaultBlockState(),ContentProperties.block("amethyst_stairs",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("amethyst_fence",()->new FenceBlock(ContentProperties.block("amethyst_fence",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("amethyst_leaves",()->new HarvestLeaves("amethyst",ContentProperties.block("amethyst_leaves",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES))),false,false);
        addBlock("amethyst_sapling",()->new CalculatorSapling(false,new TreeGrower("foundations_calculator:amethyst",Optional.empty(),Optional.of(ResourceKey.create(Registries.CONFIGURED_FEATURE,id("amethyst_tree"))),Optional.empty()),ContentProperties.block("amethyst_sapling",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING))),false,false);
        addBlock("tanzanite_log",()->new RotatedPillarBlock(ContentProperties.block("tanzanite_log",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG))),false,false);
        addBlock("tanzanite_planks",()->new Block(ContentProperties.block("tanzanite_planks",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("tanzanite_stairs",()->new StairBlock(block("tanzanite_planks").defaultBlockState(),ContentProperties.block("tanzanite_stairs",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("tanzanite_fence",()->new FenceBlock(ContentProperties.block("tanzanite_fence",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("tanzanite_leaves",()->new HarvestLeaves("tanzanite",ContentProperties.block("tanzanite_leaves",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES))),false,false);
        addBlock("tanzanite_sapling",()->new CalculatorSapling(false,new TreeGrower("foundations_calculator:tanzanite",Optional.empty(),Optional.of(ResourceKey.create(Registries.CONFIGURED_FEATURE,id("tanzanite_tree"))),Optional.empty()),ContentProperties.block("tanzanite_sapling",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING))),false,false);
        addBlock("pear_log",()->new RotatedPillarBlock(ContentProperties.block("pear_log",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG))),false,false);
        addBlock("pear_planks",()->new Block(ContentProperties.block("pear_planks",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("pear_stairs",()->new StairBlock(block("pear_planks").defaultBlockState(),ContentProperties.block("pear_stairs",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("pear_fence",()->new FenceBlock(ContentProperties.block("pear_fence",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("pear_leaves",()->new HarvestLeaves("pear",ContentProperties.block("pear_leaves",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES))),false,false);
        addBlock("pear_sapling",()->new CalculatorSapling(false,new TreeGrower("foundations_calculator:pear",Optional.empty(),Optional.of(ResourceKey.create(Registries.CONFIGURED_FEATURE,id("pear_tree"))),Optional.empty()),ContentProperties.block("pear_sapling",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING))),false,false);
        addBlock("diamond_log",()->new RotatedPillarBlock(ContentProperties.block("diamond_log",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG))),false,false);
        addBlock("diamond_planks",()->new Block(ContentProperties.block("diamond_planks",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("diamond_stairs",()->new StairBlock(block("diamond_planks").defaultBlockState(),ContentProperties.block("diamond_stairs",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("diamond_fence",()->new FenceBlock(ContentProperties.block("diamond_fence",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("diamond_leaves",()->new HarvestLeaves("diamond",ContentProperties.block("diamond_leaves",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES))),false,false);
        addBlock("diamond_sapling",()->new CalculatorSapling(true,new TreeGrower("foundations_calculator:diamond",Optional.empty(),Optional.of(ResourceKey.create(Registries.CONFIGURED_FEATURE,id("diamond_tree"))),Optional.empty()),ContentProperties.block("diamond_sapling",BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING))),false,false);
        addBlock("calculator_screen_block",()->new MachineBlock(ContentProperties.block("calculator_screen_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f).noOcclusion())),true,false);
        addBlock("crop_broccoli",()->new CalculatorCrop("broccoli_seeds",ContentProperties.block("crop_broccoli",BlockBehaviour.Properties.ofFullCopy(Blocks.WHEAT))),false,false);
        addBlock("crop_prunae",()->new CalculatorCrop("prunae_seeds",ContentProperties.block("crop_prunae",BlockBehaviour.Properties.ofFullCopy(Blocks.WHEAT))),false,false);
        addBlock("crop_fiddledew",()->new CalculatorCrop("fiddledew_fruit",ContentProperties.block("crop_fiddledew",BlockBehaviour.Properties.ofFullCopy(Blocks.WHEAT))),false,false);
        addBlock("reinforced_stone_block",()->new Block(ContentProperties.block("reinforced_stone_block",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_stairs",()->new StairBlock(block("reinforced_stone_block").defaultBlockState(),ContentProperties.block("reinforced_stone_stairs",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_fence",()->new FenceBlock(ContentProperties.block("reinforced_stone_fence",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_gate",()->new FenceGateBlock(WoodType.OAK,ContentProperties.block("reinforced_stone_gate",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_brick",()->new Block(ContentProperties.block("reinforced_stone_brick",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_brick_stairs",()->new StairBlock(block("reinforced_stone_brick").defaultBlockState(),ContentProperties.block("reinforced_stone_brick_stairs",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_brick_fence",()->new FenceBlock(ContentProperties.block("reinforced_stone_brick_fence",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_stone_brick_gate",()->new FenceGateBlock(WoodType.OAK,ContentProperties.block("reinforced_stone_brick_gate",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_block",()->new Block(ContentProperties.block("reinforced_dirt_block",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_stairs",()->new StairBlock(block("reinforced_dirt_block").defaultBlockState(),ContentProperties.block("reinforced_dirt_stairs",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_fence",()->new FenceBlock(ContentProperties.block("reinforced_dirt_fence",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_gate",()->new FenceGateBlock(WoodType.OAK,ContentProperties.block("reinforced_dirt_gate",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_brick",()->new Block(ContentProperties.block("reinforced_dirt_brick",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_brick_stairs",()->new StairBlock(block("reinforced_dirt_brick").defaultBlockState(),ContentProperties.block("reinforced_dirt_brick_stairs",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_brick_fence",()->new FenceBlock(ContentProperties.block("reinforced_dirt_brick_fence",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("reinforced_dirt_brick_gate",()->new FenceGateBlock(WoodType.OAK,ContentProperties.block("reinforced_dirt_brick_gate",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_glass",()->new ConnectedDecorBlock(ContentProperties.block("stable_glass",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion().isViewBlocking((s,w,p)->false))),false,false);
        addBlock("clear_stable_glass",()->new ConnectedDecorBlock(ContentProperties.block("clear_stable_glass",BlockBehaviour.Properties.of().strength(1.0f,12.0f).noOcclusion().isViewBlocking((s,w,p)->false))),false,false);
        addBlock("amethyst_block",()->new Block(ContentProperties.block("amethyst_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("tanzanite_block",()->new Block(ContentProperties.block("tanzanite_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("enriched_gold_block",()->new Block(ContentProperties.block("enriched_gold_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("reinforced_iron_block",()->new Block(ContentProperties.block("reinforced_iron_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("weakened_diamond_block",()->new Block(ContentProperties.block("weakened_diamond_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("flawless_diamond_block",()->new Block(ContentProperties.block("flawless_diamond_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("fire_diamond_block",()->new Block(ContentProperties.block("fire_diamond_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("electric_diamond_block",()->new Block(ContentProperties.block("electric_diamond_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("end_diamond_block",()->new Block(ContentProperties.block("end_diamond_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("redstone_ingot_block",()->new Block(ContentProperties.block("redstone_ingot_block",BlockBehaviour.Properties.of().strength(2.0f,10.0f))),false,false);
        addBlock("stable_stone_normal",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_normal",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_brown",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_brown",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_cyan",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_cyan",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_green",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_green",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_light_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_light_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_light_grey",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_light_grey",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_lime",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_lime",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_magenta",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_magenta",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_orange",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_orange",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_pink",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_pink",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_plain",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_plain",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_purple",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_purple",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_red",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_red",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_yellow",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_yellow",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_normal",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_normal",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_black",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_black",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_brown",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_brown",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_cyan",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_cyan",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_green",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_green",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_light_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_light_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_light_grey",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_light_grey",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_lime",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_lime",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_magenta",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_magenta",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_orange",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_orange",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_pink",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_pink",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_plain",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_plain",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_purple",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_purple",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_red",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_red",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_rimmed_yellow",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_rimmed_yellow",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_normal",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_normal",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_black",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_black",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_brown",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_brown",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_cyan",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_cyan",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_green",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_green",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_light_blue",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_light_blue",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_light_grey",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_light_grey",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_lime",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_lime",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_magenta",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_magenta",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_orange",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_orange",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_pink",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_pink",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_plain",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_plain",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_purple",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_purple",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_red",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_red",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        addBlock("stable_stone_black_rimmed_yellow",()->new ConnectedDecorBlock(ContentProperties.block("stable_stone_black_rimmed_yellow",BlockBehaviour.Properties.of().strength(1.0f,12.0f))),false,false);
        ITEMS_BY_ID.put("info_calculator",ITEMS.register("info_calculator",()->new CalculatorItem("info_calculator",0,ContentProperties.item("info_calculator",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("calculator",ITEMS.register("calculator",()->new CalculatorItem("calculator",1000,ContentProperties.item("calculator",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("crafting_calculator",ITEMS.register("crafting_calculator",()->new CalculatorItem("crafting_calculator",5000,ContentProperties.item("crafting_calculator",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("scientific_calculator",ITEMS.register("scientific_calculator",()->new CalculatorItem("scientific_calculator",2000,ContentProperties.item("scientific_calculator",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("flawless_calculator",ITEMS.register("flawless_calculator",()->new CalculatorItem("flawless_calculator",1000000,ContentProperties.item("flawless_calculator",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("storage_module",ITEMS.register("storage_module",()->new CalculatorItem("storage_module",0,ContentProperties.item("storage_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("warp_module",ITEMS.register("warp_module",()->new CalculatorItem("warp_module",10000,ContentProperties.item("warp_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("jump_module",ITEMS.register("jump_module",()->new CalculatorItem("jump_module",10000,ContentProperties.item("jump_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("hunger_module",ITEMS.register("hunger_module",()->new CalculatorItem("hunger_module",0,ContentProperties.item("hunger_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("health_module",ITEMS.register("health_module",()->new CalculatorItem("health_module",0,ContentProperties.item("health_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("nutrition_module",ITEMS.register("nutrition_module",()->new CalculatorItem("nutrition_module",0,ContentProperties.item("nutrition_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("terrain_module",ITEMS.register("terrain_module",()->new CalculatorItem("terrain_module",400,ContentProperties.item("terrain_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("advanced_terrain_module",ITEMS.register("advanced_terrain_module",()->new CalculatorItem("advanced_terrain_module",2000,ContentProperties.item("advanced_terrain_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("energy_module",ITEMS.register("energy_module",()->new CalculatorItem("energy_module",100000,ContentProperties.item("energy_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("locator_module",ITEMS.register("locator_module",()->new CalculatorItem("locator_module",0,ContentProperties.item("locator_module",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("soil",ITEMS.register("soil",()->new CalculatorItem("soil",0,ContentProperties.item("soil",new Item.Properties()))));
        ITEMS_BY_ID.put("small_stone",ITEMS.register("small_stone",()->new CalculatorItem("small_stone",0,ContentProperties.item("small_stone",new Item.Properties()))));
        ITEMS_BY_ID.put("speed_upgrade",ITEMS.register("speed_upgrade",()->new CalculatorItem("speed_upgrade",0,ContentProperties.item("speed_upgrade",new Item.Properties()))));
        ITEMS_BY_ID.put("energy_upgrade",ITEMS.register("energy_upgrade",()->new CalculatorItem("energy_upgrade",0,ContentProperties.item("energy_upgrade",new Item.Properties()))));
        ITEMS_BY_ID.put("void_upgrade",ITEMS.register("void_upgrade",()->new CalculatorItem("void_upgrade",0,ContentProperties.item("void_upgrade",new Item.Properties()))));
        ITEMS_BY_ID.put("transfer_upgrade",ITEMS.register("transfer_upgrade",()->new CalculatorItem("transfer_upgrade",0,ContentProperties.item("transfer_upgrade",new Item.Properties()))));
        ITEMS_BY_ID.put("calculator_screen",ITEMS.register("calculator_screen",()->new CalculatorItem("calculator_screen",0,ContentProperties.item("calculator_screen",new Item.Properties()))));
        ITEMS_BY_ID.put("calculator_assembly",ITEMS.register("calculator_assembly",()->new CalculatorItem("calculator_assembly",0,ContentProperties.item("calculator_assembly",new Item.Properties()))));
        ITEMS_BY_ID.put("advanced_assembly",ITEMS.register("advanced_assembly",()->new CalculatorItem("advanced_assembly",0,ContentProperties.item("advanced_assembly",new Item.Properties()))));
        ITEMS_BY_ID.put("atomic_module",ITEMS.register("atomic_module",()->new CalculatorItem("atomic_module",0,ContentProperties.item("atomic_module",new Item.Properties()))));
        ITEMS_BY_ID.put("atomic_assembly",ITEMS.register("atomic_assembly",()->new CalculatorItem("atomic_assembly",0,ContentProperties.item("atomic_assembly",new Item.Properties()))));
        ITEMS_BY_ID.put("flawless_assembly",ITEMS.register("flawless_assembly",()->new CalculatorItem("flawless_assembly",0,ContentProperties.item("flawless_assembly",new Item.Properties()))));
        ITEMS_BY_ID.put("atomic_binder",ITEMS.register("atomic_binder",()->new CalculatorItem("atomic_binder",0,ContentProperties.item("atomic_binder",new Item.Properties()))));
        ITEMS_BY_ID.put("wrench",ITEMS.register("wrench",()->new CalculatorItem("wrench",0,ContentProperties.item("wrench",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("sickle",ITEMS.register("sickle",()->new CalculatorItem("sickle",0,ContentProperties.item("sickle",new Item.Properties().stacksTo(1)))));
        ITEMS_BY_ID.put("obsidian_key",ITEMS.register("obsidian_key",()->new CalculatorItem("obsidian_key",0,ContentProperties.item("obsidian_key",new Item.Properties().durability(1000)))));
        ITEMS_BY_ID.put("reinforced_sword",ITEMS.register("reinforced_sword",()->new SwordItem(CalculatorTier.of("reinforced"),ContentProperties.item("reinforced_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("reinforced"),3,-2.4f))))));
        ITEMS_BY_ID.put("enriched_gold_sword",ITEMS.register("enriched_gold_sword",()->new SwordItem(CalculatorTier.of("enriched_gold"),ContentProperties.item("enriched_gold_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("enriched_gold"),3,-2.4f))))));
        ITEMS_BY_ID.put("reinforced_iron_sword",ITEMS.register("reinforced_iron_sword",()->new SwordItem(CalculatorTier.of("reinforced_iron"),ContentProperties.item("reinforced_iron_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("reinforced_iron"),3,-2.4f))))));
        ITEMS_BY_ID.put("redstone_sword",ITEMS.register("redstone_sword",()->new SwordItem(CalculatorTier.of("redstone"),ContentProperties.item("redstone_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("redstone"),3,-2.4f))))));
        ITEMS_BY_ID.put("weakened_diamond_sword",ITEMS.register("weakened_diamond_sword",()->new SwordItem(CalculatorTier.of("weakened_diamond"),ContentProperties.item("weakened_diamond_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("weakened_diamond"),3,-2.4f))))));
        ITEMS_BY_ID.put("flawless_diamond_sword",ITEMS.register("flawless_diamond_sword",()->new SwordItem(CalculatorTier.of("flawless_diamond"),ContentProperties.item("flawless_diamond_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("flawless_diamond"),3,-2.4f))))));
        ITEMS_BY_ID.put("fire_diamond_sword",ITEMS.register("fire_diamond_sword",()->new FireSwordItem(CalculatorTier.of("fire_diamond"),ContentProperties.item("fire_diamond_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("fire_diamond"),3,-2.4f))))));
        ITEMS_BY_ID.put("electric_sword",ITEMS.register("electric_sword",()->new SwordItem(CalculatorTier.of("electric"),ContentProperties.item("electric_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("electric"),3,-2.4f))))));
        ITEMS_BY_ID.put("end_forged_sword",ITEMS.register("end_forged_sword",()->new SwordItem(CalculatorTier.of("end_forged"),ContentProperties.item("end_forged_sword",new Item.Properties().attributes(SwordItem.createAttributes(CalculatorTier.of("end_forged"),3,-2.4f)).component(DataComponents.UNBREAKABLE,new Unbreakable(true))))));
        ITEMS_BY_ID.put("reinforced_pickaxe",ITEMS.register("reinforced_pickaxe",()->new PickaxeItem(CalculatorTier.of("reinforced"),ContentProperties.item("reinforced_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("reinforced"),1f,-2.8f))))));
        ITEMS_BY_ID.put("enriched_gold_pickaxe",ITEMS.register("enriched_gold_pickaxe",()->new PickaxeItem(CalculatorTier.of("enriched_gold"),ContentProperties.item("enriched_gold_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("enriched_gold"),1f,-2.8f))))));
        ITEMS_BY_ID.put("reinforced_iron_pickaxe",ITEMS.register("reinforced_iron_pickaxe",()->new PickaxeItem(CalculatorTier.of("reinforced_iron"),ContentProperties.item("reinforced_iron_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("reinforced_iron"),1f,-2.8f))))));
        ITEMS_BY_ID.put("redstone_pickaxe",ITEMS.register("redstone_pickaxe",()->new PickaxeItem(CalculatorTier.of("redstone"),ContentProperties.item("redstone_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("redstone"),1f,-2.8f))))));
        ITEMS_BY_ID.put("weakened_diamond_pickaxe",ITEMS.register("weakened_diamond_pickaxe",()->new PickaxeItem(CalculatorTier.of("weakened_diamond"),ContentProperties.item("weakened_diamond_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("weakened_diamond"),1f,-2.8f))))));
        ITEMS_BY_ID.put("flawless_diamond_pickaxe",ITEMS.register("flawless_diamond_pickaxe",()->new PickaxeItem(CalculatorTier.of("flawless_diamond"),ContentProperties.item("flawless_diamond_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("flawless_diamond"),1f,-2.8f))))));
        ITEMS_BY_ID.put("fire_diamond_pickaxe",ITEMS.register("fire_diamond_pickaxe",()->new PickaxeItem(CalculatorTier.of("fire_diamond"),ContentProperties.item("fire_diamond_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("fire_diamond"),1f,-2.8f))))));
        ITEMS_BY_ID.put("electric_pickaxe",ITEMS.register("electric_pickaxe",()->new PickaxeItem(CalculatorTier.of("electric"),ContentProperties.item("electric_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("electric"),1f,-2.8f))))));
        ITEMS_BY_ID.put("end_forged_pickaxe",ITEMS.register("end_forged_pickaxe",()->new PickaxeItem(CalculatorTier.of("end_forged"),ContentProperties.item("end_forged_pickaxe",new Item.Properties().attributes(PickaxeItem.createAttributes(CalculatorTier.of("end_forged"),1f,-2.8f)).component(DataComponents.UNBREAKABLE,new Unbreakable(true))))));
        ITEMS_BY_ID.put("reinforced_axe",ITEMS.register("reinforced_axe",()->new AxeItem(CalculatorTier.of("reinforced"),ContentProperties.item("reinforced_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("reinforced"),6f,-3.0f))))));
        ITEMS_BY_ID.put("enriched_gold_axe",ITEMS.register("enriched_gold_axe",()->new AxeItem(CalculatorTier.of("enriched_gold"),ContentProperties.item("enriched_gold_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("enriched_gold"),6f,-3.0f))))));
        ITEMS_BY_ID.put("reinforced_iron_axe",ITEMS.register("reinforced_iron_axe",()->new AxeItem(CalculatorTier.of("reinforced_iron"),ContentProperties.item("reinforced_iron_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("reinforced_iron"),6f,-3.0f))))));
        ITEMS_BY_ID.put("redstone_axe",ITEMS.register("redstone_axe",()->new AxeItem(CalculatorTier.of("redstone"),ContentProperties.item("redstone_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("redstone"),6f,-3.0f))))));
        ITEMS_BY_ID.put("weakened_diamond_axe",ITEMS.register("weakened_diamond_axe",()->new AxeItem(CalculatorTier.of("weakened_diamond"),ContentProperties.item("weakened_diamond_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("weakened_diamond"),6f,-3.0f))))));
        ITEMS_BY_ID.put("flawless_diamond_axe",ITEMS.register("flawless_diamond_axe",()->new AxeItem(CalculatorTier.of("flawless_diamond"),ContentProperties.item("flawless_diamond_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("flawless_diamond"),6f,-3.0f))))));
        ITEMS_BY_ID.put("fire_diamond_axe",ITEMS.register("fire_diamond_axe",()->new AxeItem(CalculatorTier.of("fire_diamond"),ContentProperties.item("fire_diamond_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("fire_diamond"),6f,-3.0f))))));
        ITEMS_BY_ID.put("electric_axe",ITEMS.register("electric_axe",()->new AxeItem(CalculatorTier.of("electric"),ContentProperties.item("electric_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("electric"),6f,-3.0f))))));
        ITEMS_BY_ID.put("end_forged_axe",ITEMS.register("end_forged_axe",()->new AxeItem(CalculatorTier.of("end_forged"),ContentProperties.item("end_forged_axe",new Item.Properties().attributes(AxeItem.createAttributes(CalculatorTier.of("end_forged"),6f,-3.0f)).component(DataComponents.UNBREAKABLE,new Unbreakable(true))))));
        ITEMS_BY_ID.put("reinforced_shovel",ITEMS.register("reinforced_shovel",()->new ShovelItem(CalculatorTier.of("reinforced"),ContentProperties.item("reinforced_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("reinforced"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("enriched_gold_shovel",ITEMS.register("enriched_gold_shovel",()->new ShovelItem(CalculatorTier.of("enriched_gold"),ContentProperties.item("enriched_gold_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("enriched_gold"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("reinforced_iron_shovel",ITEMS.register("reinforced_iron_shovel",()->new ShovelItem(CalculatorTier.of("reinforced_iron"),ContentProperties.item("reinforced_iron_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("reinforced_iron"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("redstone_shovel",ITEMS.register("redstone_shovel",()->new ShovelItem(CalculatorTier.of("redstone"),ContentProperties.item("redstone_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("redstone"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("weakened_diamond_shovel",ITEMS.register("weakened_diamond_shovel",()->new ShovelItem(CalculatorTier.of("weakened_diamond"),ContentProperties.item("weakened_diamond_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("weakened_diamond"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("flawless_diamond_shovel",ITEMS.register("flawless_diamond_shovel",()->new ShovelItem(CalculatorTier.of("flawless_diamond"),ContentProperties.item("flawless_diamond_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("flawless_diamond"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("fire_diamond_shovel",ITEMS.register("fire_diamond_shovel",()->new ShovelItem(CalculatorTier.of("fire_diamond"),ContentProperties.item("fire_diamond_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("fire_diamond"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("electric_shovel",ITEMS.register("electric_shovel",()->new ShovelItem(CalculatorTier.of("electric"),ContentProperties.item("electric_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("electric"),1.5f,-3.0f))))));
        ITEMS_BY_ID.put("end_forged_shovel",ITEMS.register("end_forged_shovel",()->new ShovelItem(CalculatorTier.of("end_forged"),ContentProperties.item("end_forged_shovel",new Item.Properties().attributes(ShovelItem.createAttributes(CalculatorTier.of("end_forged"),1.5f,-3.0f)).component(DataComponents.UNBREAKABLE,new Unbreakable(true))))));
        ITEMS_BY_ID.put("reinforced_hoe",ITEMS.register("reinforced_hoe",()->new HoeItem(CalculatorTier.of("reinforced"),ContentProperties.item("reinforced_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("reinforced"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("enriched_gold_hoe",ITEMS.register("enriched_gold_hoe",()->new HoeItem(CalculatorTier.of("enriched_gold"),ContentProperties.item("enriched_gold_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("enriched_gold"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("reinforced_iron_hoe",ITEMS.register("reinforced_iron_hoe",()->new HoeItem(CalculatorTier.of("reinforced_iron"),ContentProperties.item("reinforced_iron_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("reinforced_iron"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("redstone_hoe",ITEMS.register("redstone_hoe",()->new HoeItem(CalculatorTier.of("redstone"),ContentProperties.item("redstone_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("redstone"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("weakened_diamond_hoe",ITEMS.register("weakened_diamond_hoe",()->new HoeItem(CalculatorTier.of("weakened_diamond"),ContentProperties.item("weakened_diamond_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("weakened_diamond"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("flawless_diamond_hoe",ITEMS.register("flawless_diamond_hoe",()->new HoeItem(CalculatorTier.of("flawless_diamond"),ContentProperties.item("flawless_diamond_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("flawless_diamond"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("fire_diamond_hoe",ITEMS.register("fire_diamond_hoe",()->new HoeItem(CalculatorTier.of("fire_diamond"),ContentProperties.item("fire_diamond_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("fire_diamond"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("electric_hoe",ITEMS.register("electric_hoe",()->new HoeItem(CalculatorTier.of("electric"),ContentProperties.item("electric_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("electric"),-1f,-2.0f))))));
        ITEMS_BY_ID.put("end_forged_hoe",ITEMS.register("end_forged_hoe",()->new HoeItem(CalculatorTier.of("end_forged"),ContentProperties.item("end_forged_hoe",new Item.Properties().attributes(HoeItem.createAttributes(CalculatorTier.of("end_forged"),-1f,-2.0f)).component(DataComponents.UNBREAKABLE,new Unbreakable(true))))));
        ITEMS_BY_ID.put("enriched_gold",ITEMS.register("enriched_gold",()->new CalculatorItem("enriched_gold",0,ContentProperties.item("enriched_gold",new Item.Properties()))));
        ITEMS_BY_ID.put("enriched_gold_ingot",ITEMS.register("enriched_gold_ingot",()->new CalculatorItem("enriched_gold_ingot",0,ContentProperties.item("enriched_gold_ingot",new Item.Properties()))));
        ITEMS_BY_ID.put("reinforced_iron_ingot",ITEMS.register("reinforced_iron_ingot",()->new CalculatorItem("reinforced_iron_ingot",0,ContentProperties.item("reinforced_iron_ingot",new Item.Properties()))));
        ITEMS_BY_ID.put("redstone_ingot",ITEMS.register("redstone_ingot",()->new CalculatorItem("redstone_ingot",0,ContentProperties.item("redstone_ingot",new Item.Properties()))));
        ITEMS_BY_ID.put("weakened_diamond",ITEMS.register("weakened_diamond",()->new CalculatorItem("weakened_diamond",0,ContentProperties.item("weakened_diamond",new Item.Properties()))));
        ITEMS_BY_ID.put("flawless_diamond",ITEMS.register("flawless_diamond",()->new CalculatorItem("flawless_diamond",0,ContentProperties.item("flawless_diamond",new Item.Properties()))));
        ITEMS_BY_ID.put("fire_diamond",ITEMS.register("fire_diamond",()->new Item(ContentProperties.item("fire_diamond",new Item.Properties()))));
        ITEMS_BY_ID.put("electric_diamond",ITEMS.register("electric_diamond",()->new CalculatorItem("electric_diamond",0,ContentProperties.item("electric_diamond",new Item.Properties()))));
        ITEMS_BY_ID.put("end_diamond",ITEMS.register("end_diamond",()->new CalculatorItem("end_diamond",0,ContentProperties.item("end_diamond",new Item.Properties()))));
        ITEMS_BY_ID.put("large_amethyst",ITEMS.register("large_amethyst",()->new CalculatorItem("large_amethyst",0,ContentProperties.item("large_amethyst",new Item.Properties()))));
        ITEMS_BY_ID.put("small_amethyst",ITEMS.register("small_amethyst",()->new CalculatorItem("small_amethyst",0,ContentProperties.item("small_amethyst",new Item.Properties()))));
        ITEMS_BY_ID.put("shard_amethyst",ITEMS.register("shard_amethyst",()->new CalculatorItem("shard_amethyst",0,ContentProperties.item("shard_amethyst",new Item.Properties()))));
        ITEMS_BY_ID.put("large_tanzanite",ITEMS.register("large_tanzanite",()->new CalculatorItem("large_tanzanite",0,ContentProperties.item("large_tanzanite",new Item.Properties()))));
        ITEMS_BY_ID.put("small_tanzanite",ITEMS.register("small_tanzanite",()->new CalculatorItem("small_tanzanite",0,ContentProperties.item("small_tanzanite",new Item.Properties()))));
        ITEMS_BY_ID.put("shard_tanzanite",ITEMS.register("shard_tanzanite",()->new CalculatorItem("shard_tanzanite",0,ContentProperties.item("shard_tanzanite",new Item.Properties()))));
        ITEMS_BY_ID.put("broccoli_seeds",ITEMS.register("broccoli_seeds",()->new GreenhouseSeedItem(block("crop_broccoli"),ContentProperties.item("broccoli_seeds",new Item.Properties()))));
        ITEMS_BY_ID.put("prunae_seeds",ITEMS.register("prunae_seeds",()->new GreenhouseSeedItem(block("crop_prunae"),ContentProperties.item("prunae_seeds",new Item.Properties()))));
        ITEMS_BY_ID.put("fiddledew_fruit",ITEMS.register("fiddledew_fruit",()->new GreenhouseSeedItem(block("crop_fiddledew"),ContentProperties.item("fiddledew_fruit",new Item.Properties().food(new FoodProperties.Builder().nutrition(16).saturationModifier(.6f).build())))));
        ITEMS_BY_ID.put("broccoli",ITEMS.register("broccoli",()->new Item(ContentProperties.item("broccoli",new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationModifier(0.2f).build())))));
        ITEMS_BY_ID.put("pear",ITEMS.register("pear",()->new Item(ContentProperties.item("pear",new Item.Properties().food(new FoodProperties.Builder().nutrition(12).saturationModifier(2.0f).build())))));
        ITEMS_BY_ID.put("rotten_pear",ITEMS.register("rotten_pear",()->new Item(ContentProperties.item("rotten_pear",new Item.Properties().food(new FoodProperties.Builder().nutrition(1).saturationModifier(0.1f).build())))));
        ITEMS_BY_ID.put("cooked_broccoli",ITEMS.register("cooked_broccoli",()->new Item(ContentProperties.item("cooked_broccoli",new Item.Properties().food(new FoodProperties.Builder().nutrition(9).saturationModifier(0.6f).build())))));
        ITEMS_BY_ID.put("coal_dust",ITEMS.register("coal_dust",()->new Item(ContentProperties.item("coal_dust",new Item.Properties()))));
        ITEMS_BY_ID.put("enriched_coal",ITEMS.register("enriched_coal",()->new Item(ContentProperties.item("enriched_coal",new Item.Properties()))));
        ITEMS_BY_ID.put("purified_coal",ITEMS.register("purified_coal",()->new Item(ContentProperties.item("purified_coal",new Item.Properties()))));
        ITEMS_BY_ID.put("fire_coal",ITEMS.register("fire_coal",()->new Item(ContentProperties.item("fire_coal",new Item.Properties()))));
        ITEMS_BY_ID.put("controlled_fuel",ITEMS.register("controlled_fuel",()->new Item(ContentProperties.item("controlled_fuel",new Item.Properties()))));
        ITEMS_BY_ID.put("grenade_casing",ITEMS.register("grenade_casing",()->new CalculatorItem("grenade_casing",0,ContentProperties.item("grenade_casing",new Item.Properties()))));
        ITEMS_BY_ID.put("baby_grenade",ITEMS.register("baby_grenade",()->new CalculatorItem("baby_grenade",0,ContentProperties.item("baby_grenade",new Item.Properties()))));
        ITEMS_BY_ID.put("grenade",ITEMS.register("grenade",()->new CalculatorItem("grenade",0,ContentProperties.item("grenade",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_0",ITEMS.register("circuit_board_0",()->new CalculatorItem("circuit_board_0",0,ContentProperties.item("circuit_board_0",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_1",ITEMS.register("circuit_board_1",()->new CalculatorItem("circuit_board_1",0,ContentProperties.item("circuit_board_1",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_2",ITEMS.register("circuit_board_2",()->new CalculatorItem("circuit_board_2",0,ContentProperties.item("circuit_board_2",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_3",ITEMS.register("circuit_board_3",()->new CalculatorItem("circuit_board_3",0,ContentProperties.item("circuit_board_3",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_4",ITEMS.register("circuit_board_4",()->new CalculatorItem("circuit_board_4",0,ContentProperties.item("circuit_board_4",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_5",ITEMS.register("circuit_board_5",()->new CalculatorItem("circuit_board_5",0,ContentProperties.item("circuit_board_5",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_6",ITEMS.register("circuit_board_6",()->new CalculatorItem("circuit_board_6",0,ContentProperties.item("circuit_board_6",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_7",ITEMS.register("circuit_board_7",()->new CalculatorItem("circuit_board_7",0,ContentProperties.item("circuit_board_7",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_8",ITEMS.register("circuit_board_8",()->new CalculatorItem("circuit_board_8",0,ContentProperties.item("circuit_board_8",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_9",ITEMS.register("circuit_board_9",()->new CalculatorItem("circuit_board_9",0,ContentProperties.item("circuit_board_9",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_10",ITEMS.register("circuit_board_10",()->new CalculatorItem("circuit_board_10",0,ContentProperties.item("circuit_board_10",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_11",ITEMS.register("circuit_board_11",()->new CalculatorItem("circuit_board_11",0,ContentProperties.item("circuit_board_11",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_12",ITEMS.register("circuit_board_12",()->new CalculatorItem("circuit_board_12",0,ContentProperties.item("circuit_board_12",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_board_13",ITEMS.register("circuit_board_13",()->new CalculatorItem("circuit_board_13",0,ContentProperties.item("circuit_board_13",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_0",ITEMS.register("circuit_dirty_0",()->new CalculatorItem("circuit_dirty_0",0,ContentProperties.item("circuit_dirty_0",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_1",ITEMS.register("circuit_dirty_1",()->new CalculatorItem("circuit_dirty_1",0,ContentProperties.item("circuit_dirty_1",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_2",ITEMS.register("circuit_dirty_2",()->new CalculatorItem("circuit_dirty_2",0,ContentProperties.item("circuit_dirty_2",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_3",ITEMS.register("circuit_dirty_3",()->new CalculatorItem("circuit_dirty_3",0,ContentProperties.item("circuit_dirty_3",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_4",ITEMS.register("circuit_dirty_4",()->new CalculatorItem("circuit_dirty_4",0,ContentProperties.item("circuit_dirty_4",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_5",ITEMS.register("circuit_dirty_5",()->new CalculatorItem("circuit_dirty_5",0,ContentProperties.item("circuit_dirty_5",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_6",ITEMS.register("circuit_dirty_6",()->new CalculatorItem("circuit_dirty_6",0,ContentProperties.item("circuit_dirty_6",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_7",ITEMS.register("circuit_dirty_7",()->new CalculatorItem("circuit_dirty_7",0,ContentProperties.item("circuit_dirty_7",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_8",ITEMS.register("circuit_dirty_8",()->new CalculatorItem("circuit_dirty_8",0,ContentProperties.item("circuit_dirty_8",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_9",ITEMS.register("circuit_dirty_9",()->new CalculatorItem("circuit_dirty_9",0,ContentProperties.item("circuit_dirty_9",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_10",ITEMS.register("circuit_dirty_10",()->new CalculatorItem("circuit_dirty_10",0,ContentProperties.item("circuit_dirty_10",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_11",ITEMS.register("circuit_dirty_11",()->new CalculatorItem("circuit_dirty_11",0,ContentProperties.item("circuit_dirty_11",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_12",ITEMS.register("circuit_dirty_12",()->new CalculatorItem("circuit_dirty_12",0,ContentProperties.item("circuit_dirty_12",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_dirty_13",ITEMS.register("circuit_dirty_13",()->new CalculatorItem("circuit_dirty_13",0,ContentProperties.item("circuit_dirty_13",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_0",ITEMS.register("circuit_damaged_0",()->new CalculatorItem("circuit_damaged_0",0,ContentProperties.item("circuit_damaged_0",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_1",ITEMS.register("circuit_damaged_1",()->new CalculatorItem("circuit_damaged_1",0,ContentProperties.item("circuit_damaged_1",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_2",ITEMS.register("circuit_damaged_2",()->new CalculatorItem("circuit_damaged_2",0,ContentProperties.item("circuit_damaged_2",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_3",ITEMS.register("circuit_damaged_3",()->new CalculatorItem("circuit_damaged_3",0,ContentProperties.item("circuit_damaged_3",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_4",ITEMS.register("circuit_damaged_4",()->new CalculatorItem("circuit_damaged_4",0,ContentProperties.item("circuit_damaged_4",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_5",ITEMS.register("circuit_damaged_5",()->new CalculatorItem("circuit_damaged_5",0,ContentProperties.item("circuit_damaged_5",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_6",ITEMS.register("circuit_damaged_6",()->new CalculatorItem("circuit_damaged_6",0,ContentProperties.item("circuit_damaged_6",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_7",ITEMS.register("circuit_damaged_7",()->new CalculatorItem("circuit_damaged_7",0,ContentProperties.item("circuit_damaged_7",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_8",ITEMS.register("circuit_damaged_8",()->new CalculatorItem("circuit_damaged_8",0,ContentProperties.item("circuit_damaged_8",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_9",ITEMS.register("circuit_damaged_9",()->new CalculatorItem("circuit_damaged_9",0,ContentProperties.item("circuit_damaged_9",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_10",ITEMS.register("circuit_damaged_10",()->new CalculatorItem("circuit_damaged_10",0,ContentProperties.item("circuit_damaged_10",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_11",ITEMS.register("circuit_damaged_11",()->new CalculatorItem("circuit_damaged_11",0,ContentProperties.item("circuit_damaged_11",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_12",ITEMS.register("circuit_damaged_12",()->new CalculatorItem("circuit_damaged_12",0,ContentProperties.item("circuit_damaged_12",new Item.Properties()))));
        ITEMS_BY_ID.put("circuit_damaged_13",ITEMS.register("circuit_damaged_13",()->new CalculatorItem("circuit_damaged_13",0,ContentProperties.item("circuit_damaged_13",new Item.Properties()))));
        TABS.register("calculator",()->CreativeModeTab.builder().title(Component.literal("Foundations Calculator")).icon(()->new ItemStack(item("calculator"))).displayItems((p,out)->ITEMS_BY_ID.forEach((name,entry)->{if(!name.startsWith("crop_")&&!PENDING.contains(name))out.accept(entry.get());})).build());
    }
    private static void addBlock(String id,Supplier<Block> factory,boolean machine,boolean pending){
        var b=BLOCKS.register(id,factory);BLOCKS_BY_ID.put(id,b);if(machine)MACHINE_BLOCKS.add(b);
        if(!id.startsWith("crop_"))ITEMS_BY_ID.put(id,ITEMS.register(id,()->new BlockItem(b.get(),ContentProperties.item(id,new Item.Properties())){
            public void appendHoverText(ItemStack s,TooltipContext c,List<Component> tooltip,TooltipFlag f){super.appendHoverText(s,c,tooltip,f);if(pending)tooltip.add(Component.literal("Port pending — not functional in this alpha").withStyle(net.minecraft.ChatFormatting.RED));}
        }));
    }
    public static ResourceLocation id(String s){return ResourceLocation.fromNamespaceAndPath(FoundationsCalculator.ID,s);}
    public static Item item(String id){var item=ITEMS_BY_ID.get(id);if(item==null)throw new IllegalArgumentException("Unknown item "+id);return item.get();}
    public static Block block(String id){return BLOCKS_BY_ID.get(id).get();}
    public static String path(ItemStack s){return BuiltInRegistries.ITEM.getKey(s.getItem()).getPath();}
    public static void register(IEventBus bus){BLOCKS.register(bus);ITEMS.register(bus);ENTITIES.register(bus);PROJECTILES.register(bus);MENUS.register(bus);TYPES.register(bus);SERIALIZERS.register(bus);COMPONENTS.register(bus);TABS.register(bus);bus.addListener(net.neoforged.bus.api.EventPriority.HIGHEST,Content::capabilities);}
    private static void capabilities(RegisterCapabilitiesEvent e){
        e.registerBlockEntity(Capabilities.EnergyStorage.BLOCK,MACHINE_ENTITY.get(),(m,side)->com.foundations.calculator.core.PowerPolicy.guardFE(m.energyPort(side),com.foundations.calculator.core.PowerPolicy.Scope.BLOCK));
        e.registerBlockEntity(Capabilities.ItemHandler.BLOCK,MACHINE_ENTITY.get(),MachineBlockEntity::automation);
        for(var entry:ITEMS_BY_ID.values())if(entry.get() instanceof CalculatorItem c&&c.capacity>0)e.registerItem(Capabilities.EnergyStorage.ITEM,(stack,ctx)->com.foundations.calculator.core.PowerPolicy.guardFE(c.storage(stack),com.foundations.calculator.core.PowerPolicy.Scope.ITEM),c);
    }
}
