from pathlib import Path
import json,re,collections,hashlib
P=Path(__file__).resolve().parents[1]
R=P/'src/main/resources/assets/foundations_calculator/foundations_guides/field_guide'
NS='foundations_calculator:'
chapters=[('getting_started','Getting started'),('calculators','Calculators & modules'),('circuits','Processing & circuits'),('power','Power & conversion'),('machines','Machine reference'),('multiblocks','Multiblock construction'),('farming','Farming & nutrition'),('research','Research & mastery'),('troubleshooting','Automation & troubleshooting'),('pack_authors','Pack authors & guide API')]
entries=[]
def block(t,text='',target='',rows=None,**options):
 d={'type':t}
 if text:d['text']=text
 if target:d['target']=target
 if rows is not None:d['rows']=rows
 if options:d['options']={k:str(v) for k,v in options.items()}
 return d
def p(t):return block('paragraph',t)
def h(t):return block('heading',t)
def note(t):return block('callout',t)
def steps(*rows):return block('steps',rows=[[r] for r in rows])
def table(title,*rows):return block('table',title,rows=[list(r) for r in rows])
def link(id,title):return block('link',title,NS+id)
def recipe(q,title='Recipes from this server',profile=''):return block('recipe',title,q,profile=profile)
def live(key,title='Actual server settings'):return block('live',title,'foundations_calculator',key=key)
def item(id,text=''):return block('item',text,NS+id)
def add(chapter,slug,title,blocks,items=(),keywords=()):
 d={'id':NS+chapter+'/'+slug,'chapter':NS+chapter,'title':title,'order':len(entries),'items':[i if ':' in i else NS+i for i in items], 'keywords':list(keywords),'blocks':blocks}
 entries.append(d);return d
add('getting_started','welcome','Welcome to Foundations Calculator',[
 p('Welcome to Foundations Calculator. This Field Guide is the home manual for the mod: calculators, machines, circuits, research, power systems, greenhouses, automation and troubleshooting all live here. You can read it from the Calculator book itself, through a compatible master-guide reader, or through the generated Patchouli mirror when Patchouli is installed.'),
 h('Start here if this is your first time'),
 steps('Open Getting Started: First 10 Minutes. It gives you a short route from your first Calculator to your first powered processing machine.','Use the search box whenever you know the name of a machine, material, circuit state or symptom.','Follow blue related-entry links instead of trying to memorize the whole book. Back and Forward preserve your reading trail.','When a page shows live values, those values come from the current server. Static examples are labelled as defaults and can differ in a customized pack.'),
 note('This guide explains the mod; it does not grant research or bypass server progression. Reading an entry, Patchouli page, or master-guide page never unlocks a recipe by itself.'),
 h('One guide, several readers'),
 p('The same Foundations Guide API content remains available to a future master-guide mod. Calculator also publishes a resource-only Patchouli mirror under foundations_calculator:field_guide. Patchouli does not create a second Calculator book item: it is told to use the existing Foundations Calculator Field Guide item.'),
 link('getting_started/quickstart','Getting Started: First 10 Minutes'),link('getting_started/first_workshop','Build your first workshop'),link('power/eu_conversion','Understand EU, FE and joules'),link('troubleshooting/no_progress','Machine powered but not processing'),live('research','Your existing research and mastery')
],['info_calculator'],['welcome','manual','book','help','start','patchouli','master guide'])
add('getting_started','quickstart','Getting Started: First 10 Minutes',[
 p('This page is the shortest practical route into Calculator. It intentionally avoids a giant shopping list because recipes, power costs and research requirements can be changed by the server or pack.'),
 steps('Craft the Calculator using the live recipe below. Keep the Field Guide nearby: the same item can always bring you back to these instructions.','Make or connect a basic power source. The Hand-Cranked Generator is the built-in early option; an external FE source also works when its route is enabled.','Place a Power Cube if you want a visible energy buffer between generation and machines. Set its sides so energy enters from the source and exits toward the machine.','Craft an Extraction Chamber. Feed it a valid early input such as the recipe list shows, supply the full batch energy, and leave output space.','When you get Dirty or Damaged circuit material, do not put it directly into Analysis. Restore Dirty chips, Reassemble Damaged chips, then Analyse clean boards.','Build a Research Chamber when a recipe says it is locked. Study the required sample; the guide can show your current research snapshot but reading the page does not unlock it.','After one manual batch works, configure item sides and automation. Test one connection at a time before adding Transfer Upgrades or a large pipe network.'),
 recipe('item:'+NS+'calculator','Craft the Calculator'),recipe('item:'+NS+'extraction_chamber','Craft the Extraction Chamber'),
 link('machines/hand_cranked_generator','Hand-Cranked Generator'),link('machines/power_cube','Power Cube'),link('machines/extraction_chamber','Extraction Chamber'),link('circuits/chain','Circuit processing order'),link('research/study','Research and samples'),link('getting_started/first_workshop','Continue: build a complete workshop')
],['calculator','extraction_chamber'],['quick start','first ten minutes','beginner','tutorial','first machine'])
add('getting_started','first_workshop','Your first working workshop',[
 p('Once the quick start works, expand it into a small reliable workshop: a Calculator, stable power, one or more processing machines, a Power Cube or equivalent buffer, and storage for every output. Follow live crafting and process recipes rather than a fixed shopping list.'),
 steps('Choose a Calculator recipe that matches your available inputs. Portable calculations complete when you press Calculate; their recipe time field does not create a hidden timer.','Keep generation and storage simple until you understand the energy route. Use the Power page if an EU/J/FE adapter is involved.','Use Extraction to obtain intermediate materials and circuit drops, then Restoration/Reassembly/Analysis in the correct order.','Give each placed machine enough stored energy for the complete batch and leave room for its result before diagnosing it as broken.','Run one batch manually, then enable automation only on intended sides. Input and Disabled faces are not valid export faces.','Add Research, modules, greenhouses and larger automation after the base chain is dependable. If something stops, search the symptom in Troubleshooting before changing multiple configs.'),
 recipe('machine:calculator','Basic calculations','calculator'),
 link('machines/hand_cranked_generator','Hand-Cranked Generator'),link('machines/power_cube','Power Cube'),link('machines/extraction_chamber','Extraction Chamber'),link('circuits/chain','Follow the circuit chain'),link('troubleshooting/no_progress','Machine has power but no progress')
],['calculator'],['first machine','tutorial','early game','progression','workshop'])
add('getting_started','slots','Slots, faces and completed batches',[
 p('The shared machine screen gives different machines a common layout, but the program decides which slots are valid. Do not treat every visible inventory slot as an interchangeable input.'),
 table('Typical process inventory',('Inputs','The labelled input area; special programs may reserve particular slots.'),('Outputs','Six ordinary result slots, internally 14–19.'),('Power / module','The special slot, internally 20; its role depends on the machine.'),('Upgrades','Speed, Energy, Transfer and Void where supported.')),
 p('A completed batch can put results in retained overflow while normal outputs are blocked. Ordinary operation waits rather than discarding those results. The Void Upgrade is the explicit exception: it permits overflow disposal.'),
 p('Automatic side mode follows the machine role. Input, Output and Disabled override a face. External item pipes and the Transfer Upgrade must both obey the machine automation master switch and those side modes. Energy has its own capability and direction settings.'),
 steps('Confirm the slot label and accepted ingredient, including any analysed/stable circuit requirement.','Test with no redstone signal unless the machine specifically needs one.','Empty outputs and retained overflow before assuming the recipe is broken.','Use Sides or the wrench to select the intended input and output faces.'),
 link('troubleshooting/automation','Automation rules and safe exports'),link('troubleshooting/blocked_output','Blocked output and pending results')
],keywords=['input slots','output slots','battery','pending'])
add('calculators','families','Which calculator should I use?',[
 table('Calculation families',('Basic Calculator','Two inputs; basic combinations and many research-gated conversions.'),('Scientific Calculator','Two inputs; a different recipe family, not an extra input slot.'),('Atomic Calculator','Placed three-input atomic recipes.'),('Flawless Calculator','Four-input flawless recipes plus installed modules.'),('Docking Station','Uses the family of the calculator placed in its special slot.'),('Dynamic Calculator','Three lanes: basic inputs 1–2, scientific 3–4, atomic 5–7.')),
 p('A recipe is selected from the family supported by the current device. A Scientific recipe does not become a Basic recipe because both devices have two slots. Item components, required counts and research can also distinguish apparently similar ingredients.'),
 p('Portable operations are immediate and return their container contents safely when closed. A time field in their recipe data does not create a hidden processing timer. Placed processors use their program time and server overrides.'),
 recipe('machine:scientific','Scientific examples','scientific_calculator'),recipe('machine:flawless','Flawless examples','flawless_calculator'),link('machines/docking_station','Docking Station'),link('machines/dynamic_calculator','Dynamic Calculator'),link('calculators/installing','Install and choose modules')
],['scientific_calculator','flawless_calculator'],['two inputs','three inputs','four inputs','tiers'])
add('calculators','installing','Installing and selecting modules',[
 p('The Module Workstation edits the modules stored inside a Flawless Calculator. The calculator component is the sole owner of the module contents; the workstation is not a second copy of the inventory.'),
 steps('Put the Flawless Calculator in the workstation Calculator slot.','Place supported modules in the module positions, up to the server-configured limit. The shipped maximum is 16.','Remove the Flawless Calculator. Its installed modules and their inventories travel with it.','Sneak-use the calculator to cycle the selected module. The selection label tells you which action a normal use will perform.','Return to the ordinary Flawless calculation selection when you need the four-input recipes instead of a module action.'),
 p('Atomic Assembly exposes the three-lane Dynamic Module. Flawless Assembly exposes flawless calculation. Storage remains inside its module; installed Energy Modules add storage. Installed ender pearls and grenades use FE rather than consuming the installed item.'),
 note('Not every similarly named crafting component is an installable module. In particular Atomic Module is a component, not a usable workstation module. Read the live crafting references before installing or consuming rare materials.'),
 live('module/flawless_calculator'),link('machines/module_workstation','Module Workstation reference'),link('calculators/storage_module','Storage Module')
],['atomic_assembly','flawless_assembly'],['installation','select module','shift','sneak'])
add('circuits','chain','The complete circuit-processing chain',[
 p('Circuits have both an item variant and stored analysis state. A dirty or damaged circuit, a clean unanalysed board, an analysed board and an analysed stable board are not interchangeable just because they share a number.'),
 table('Processing route',('Extraction / Precision','Find dirty or damaged circuits from their configured inputs.'),('Restoration','Clean dirty circuits into matching boards.'),('Reassembly','Repair damaged circuits into matching boards.'),('Processing','Combines the cleaning and repair roles.'),('Analysis','Analyse clean boards; reveals stability and can award items/FE.'),('Fabrication / Plugs / Multiplication','Use the exact board variants and state required by the operation.')),
 steps('Start with a raw chip and read its actual item name: Dirty or Damaged.','Select the cleaning/repair machine that handles that type.','After processing, move the resulting clean board into the Analysing Chamber.','Read the analysed/stable tooltip before placing the board in a Fabrication recipe or Calculator Plug.','Do not reinsert an already analysed board expecting another analysis reward.'),
 p('The analyser has data-driven rewards. Its board state is saved on the item. The guide shows public instructions and recipe state requirements; it does not alter the board, reroll its data, or grant rewards.'),
 link('machines/extraction_chamber','Extraction'),link('machines/precision_chamber','Precision'),link('machines/processing_chamber','Cleaning and repair'),link('machines/analysing_chamber','Analysis'),link('troubleshooting/dirty_chip','Dirty chip not running')
],['circuit_dirty_'+str(i) for i in range(14)]+['circuit_damaged_'+str(i) for i in range(14)],['dirty chip','damaged chip','circuit chain','stable'])
add('circuits','boards','Board variants, analysis and stability',[
 p('There are fourteen board variants. Matching the board number is necessary when a recipe asks for a particular variant, and a state requirement can add another condition. The recipe panel labels analysed and analysed AND stable requirements separately.'),
 p('An ordinary clean board needs analysis before it can satisfy an analysed requirement. A stable board also needs the analysed flag when a recipe requires both. Fabrication and Locator stabilization have different acceptance rules; do not infer one from the other.'),
 p('A Calculator Plug activates when it holds a stable board. The Locator counts those plugs. Its owner-presence requirement and instability behavior are described in the Locator chapter, not in the recipe browser.'),
 recipe('machine:fabrication_chamber','Fabrication requirements','fabrication_chamber'),link('machines/calculator_plug','Calculator Plug'),link('machines/calculator_locator','Calculator Locator')
],['circuit_board_'+str(i) for i in range(14)],['analysed','analyzed','circuit_state','stable board'])
add('power','eu_conversion','EU, FE, J and conversion policy',[
 p('Calculator stores FE internally. Native adapters accept or send supported external units at the boundary. EU is therefore an accepted connection type, not a replacement for the internal buffer.'),
 table('Electrical adapters',('NeoForge FE','Native FE input/output. RF/IF/CF branding is compatible only where that mod exposes FE.'),('GregTech CEu','EU packets with voltage and amperage limits; separate native battery rules.'),('Mekanism','Joules via native machine and item APIs.'),('Modern Industrialization','EU via the MI energy API.'),('GrandPower','Long-valued FE API with a 1:1 base unit.'),('Applied Energistics 2','AE-powered items only; not a direct native grid port.')),
 p('Each native adapter has independent block-port and item-charging gates, input/output gates, and applicable loss settings. Input means native energy enters Foundations storage, including discharging an external battery. Output means Foundations energy leaves storage, including charging an external battery.'),
 table('Ratio keys',('compat.gtceu.fePerEU','0 inherits the higher of GT direction ratios; a positive integer fixes FE per EU.'),('power.mekanism.joulesPerFE','0 inherits Mekanism; a positive decimal fixes J per FE.'),('power.modernIndustrialization.fePerEU','0 inherits MI; a positive decimal fixes FE per EU.'),('compat.aeEnergyToFE','FE per AE for powered items.')),
 p('Voltage is packet size and amperage is packet count per tick. Neither is the EU/FE exchange rate. Port capacity, side modes, native item tier restrictions and shared packet budgets still apply.'),
 live('power','Effective server adapters, ratios, losses and warnings'),link('power/rounding','Whole units, losses and conversion loops'),link('power/gregtech','GregTech packet rules'),link('power/routing','Which API does a connection use?')
],keywords=['EU','FE','J','joules','voltage','conversion','Mekanism','GregTech','MI','AE2'])
add('power','scaling','Long buffers, units & scale',[
 p('0.0.2a stores Calculator machine and powered-item energy with 64-bit counters. NeoForge FE remains an int-valued compatibility capability, so a single FE call is bounded even when the underlying buffer is much larger. Native long-valued adapters can see the full buffer.'),
 table('Scale controls',('energy.machineCapacityMultiplier','Multiplies every machine buffer after its normal machine capacity.'),('machine.<id>.capacityMultiplier','Per-machine multiplier applied after the configured base capacity.'),('energy.itemCapacityMultiplier','Multiplies Calculator/module item buffers.'),('module.<id>.capacityMultiplier','Per-item/module multiplier.'),('energy.transferMultiplier','Multiplies transfer/charging limits without changing conversion ratios.')),
 p('Existing R9 machine saves migrate automatically because the Energy NBT field is read as a long. Powered items retain the legacy int energy component for downgrade visibility and add a long component for values above 2,147,483,647 FE.'),
 note('Large buffers do not make one transfer unlimited. FE, GT packet limits, machine transfer rates, item charge rates, side modes and adapter policy still cap each operation.'),
 p('Client setting information.energyUnit can display FE or an explicitly configured GT EU, Mekanism J or MI EU view. If an external ratio is inherited rather than explicitly configured, the GUI falls back to FE instead of guessing.'),
 link('power/eu_conversion','EU, FE, J and conversion policy'),link('pack_authors/configuration','Pack configuration and presets')
],['power_cube','advanced_power_cube'],['long energy','capacity','buffer','preset','high power','scale'])
add('power','rounding','Whole units, losses and converter loops',[
 p('Conversions must not round a tiny offer up into free power. The long-valued bridges move exact representable quanta; a remainder stays in its original storage instead of being invented or silently claimed as transferred.'),
 table('Illustrative arithmetic, not a server setting',('2.5 J per FE, no loss','5 J converts to 2 FE; a smaller offer can be insufficient.'),('2.5 J per FE, 10% input loss','25 J converts to 9 FE.'),('4 FE per EU, 10% input loss','100 EU becomes 360 FE.'),('Same ratio, then 20% output loss','Those 360 FE become 72 EU.')),
 p('Input and output losses are independent, but the bridge uses one base ratio. Very precise ratios can require a large quantum. If that quantum exceeds the transfer rate or remaining buffer space, transfer pauses. That is not necessarily a broken cable.'),
 p('GT block packets are rounded conservatively at packet boundaries, rather than using a fictional simulated packet API. Fractional AE item operations also use conservative rounding. No simulation is supposed to debit storage.'),
 note('A safe round trip inside Calculator does not prove an entire modpack is free of converter loops. Another mod can use a different exchange rate. Prefer inherit, align all converters, or deliberately close incompatible routes. Changing rates with charged buffers changes their native-equivalent value; it does not rewrite stored FE.'),
 link('power/eu_conversion','Read the actual server ratios'),link('troubleshooting/power','Power is connected but not moving')
],keywords=['rounding','quantum','loss','free energy','loop','ratio'])
add('power','gregtech','GregTech voltage, amperage and tiers',[
 p('GT cable networks exchange complete voltage/amperage packets. Calculator does not pretend those cables are a generic simulated FE battery. Output sends only packets the target advertises it can accept; input accepts only whole packets that fit the configured limits and FE buffer.'),
 p('The shipped output is LV: 32 EU at one amp per tick. The shipped input budget is four amps per tick, shared across faces. These are defaults; the effective settings below are authoritative for your server.'),
 p('A per-machine voltage or amperage override of zero inherits the global GT value. Battery charger/item tiers are separate from the cable settings. Refused over-voltage packets do not cause Calculator to explode. GT cables still apply their own cable losses.'),
 steps('Confirm the installed GT version matches the pinned integration target in the source documentation.','Set compatible machine and cable tiers; do not use a larger ratio to imitate a voltage tier.','Set the face to the correct energy direction.','Check whether the shared per-tick amp budget is already exhausted by another face.','Use Power diagnostics on a nearby machine for the exact packet limits and refusal reason.'),
 live('power'),link('power/routing','Native routing versus FE facades')
],keywords=['LV','overvoltage','over voltage','amps','packet','battery tier'])
add('power','routing','Native routing, FE facades and charging',[
 p('With native-first routing, Calculator prefers its native adapter for an external target. If that native adapter exists but is disabled or refuses the operation, Calculator does not silently try the target’s FE facade to evade the native policy.'),
 p('Setting power.routing.preferNative to false deliberately prefers an available FE facade. A native ratio or loss then does not govern that FE path. A source in another mod chooses the capability it pushes into; Calculator cannot force that source to choose EU or J.'),
 p('Closing power.fe.blockPorts closes Calculator’s direct FE machine capability and its generic FE block sends without disabling its underlying FE store. Native adapters can still use that store when permitted. Calculator-to-Calculator transfers stay FE rather than converting twice.'),
 table('Item slots',('Power Cube Discharge','Drain a battery or supported consumable into the cube.'),('Power Cube Charge','Send stored FE into a supported powered item.'),('Processing-machine Power','Normally accept discharge into the machine.'),('Special slots','Some machines use the same slot index for a calculator, module or locator binding instead.')),
 note('Calculator machine and powered-item buffers are long-valued in 0.0.2a. NeoForge FE still moves int-sized requests, while native long adapters and the Foundations long-energy API can expose the full buffer.'),
 live('power'),link('machines/power_cube','Power Cube'),link('troubleshooting/power','Diagnose an inactive transfer')
],keywords=['native first','FE first','routing','charger','battery','GrandPower'])
add('multiblocks','coordinates','Reading controller-relative construction plans',[
 p('Every plan is relative to the controller, not fixed world north. Place it facing you. Inside is the opposite of that visible front. Side is clockwise from the inside direction. Height zero is the controller’s block level.'),
 table('Diagram symbols',('C','Controller.'),('S','Stable Stone / supported stable-stone variant.'),('G','Glass; check the entry for ordinary or Flawless Glass.'),('L','Logs.'),('P','Planks.'),('T','Wooden stair in automatic greenhouse plans.'),('W','Water or irrigation cell.'),('Q','Bottom Quartz Slab in a flawless roof.'),('.','Air / clear space, unless the layer explicitly says otherwise.')),
 p('The rows of the default diagrams run from the near/outside end toward the inside end. Columns run from negative side to positive side. A roof overhang is part of the construction bounds even when it is outside the crop footprint.'),
 p('Basic and Advanced Greenhouses build from controller inputs. Flawless Greenhouses, the Dynamic Calculator and Locator structure are manual layouts. Do not press Build expecting a manually assembled structure to appear.'),
 note('Diagrams show shipped geometry, not a live ghost overlay. Server configuration can change supported Dynamic radius or Flawless length. Check the relevant server-values block before preparing materials.'),
 link('multiblocks/basic_greenhouse','Basic Greenhouse layers'),link('multiblocks/advanced_greenhouse','Advanced Greenhouse layers'),link('multiblocks/flawless_greenhouse','Flawless manual layers'),link('multiblocks/dynamic','Dynamic Calculator layers'),link('multiblocks/locator','Locator platform')
],keywords=['orientation','front','inside','clockwise','layer','blueprint'])
# Exact default greenhouse maps generated by executing the production blueprint against isolated coordinate fixtures.
by=collections.defaultdict(dict)
for line in (P/'docs/guide/blueprint-export.tsv').read_text().splitlines():
 tier,face,x,y,z,kind,meta=line.split('\t')
 if face=='NORTH':by[int(tier)][(int(x),int(y),int(z))]=kind
for tier,slug,label in [(1,'basic_greenhouse','Basic'),(2,'advanced_greenhouse','Advanced')]:
 data=by[tier];counts=collections.Counter(data.values());xs=[p[0] for p in data];ys=[p[1] for p in data];zs=[p[2] for p in data]
 blocks=[p(f'The {label} controller constructs this imported blueprint with Build. Its first four inputs are logs, wooden stairs, glass, and planks, in that order. Fill those slots, supply FE, and remove obstructions. Construction resumes where it stopped.'),
 table('Exact default structural materials (controller, floor, water and seeds are additional)',('Logs',str(counts['LOG'])),('Wooden stairs',str(counts['STAIRS'])),('Glass',str(counts['GLASS'])),('Planks',str(counts['PLANKS'])),('Unique structural blocks',str(len(data)))),
 p(f'Clear side {min(xs)} to {max(xs)}, inside {min(zs)} to {max(zs)}, and height {min(ys)} to {max(ys)}. The diagrams below show structural blocks only. C is the existing controller; dots are not a request to replace terrain.'),
 p('Provide dirt/grass beneath the growing cells. Basic has eight crops in its 3×3 area with central water; Advanced has 45 crops in a 7×7 area with four irrigation corners. Roof stairs are oriented by automatic construction, so supply stairs rather than placing a flat slab roof.'),
 note('R7 owner/protection preflights still apply. Missing owner, denied target, unloaded chunk or obstruction can stop a build. Never bypass a claim merely to complete a diagram. Demolish only recovers matching blocks after removal succeeds.')]
 for y in range(min(ys),max(ys)+1):
  rows=[]
  for z in range(min(zs),max(zs)+1):
   row=''
   for x in range(min(xs),max(xs)+1):row+=('C' if (x,y,z)==(0,0,0) else {'LOG':'L','STAIRS':'T','GLASS':'G','PLANKS':'P'}.get(data.get((x,y,z)),'.'))
   rows.append([row])
  blocks.append(block('layers',f'Height {y}; inside increases downward',rows=rows,legend='L logs · T stairs · G glass · P planks · C controller'))
 blocks += [live('machine/'+slug),link('farming/growing','Planting and greenhouse operation'),link('troubleshooting/construction','Construction stopped')]
 add('multiblocks',slug,label+' Greenhouse: complete default layers',blocks,keywords=['blueprint','roof','stairs','dimensions','material list'])
add('multiblocks','flawless_greenhouse','Flawless Greenhouse: manual frame and roof',[
 p('Build this greenhouse manually. Choose an interior length L within the server limit (shipped maximum 64). Its total width is four blocks. The controller is side 0, inside 0, height 0. The two central columns hold crops; the outer columns provide walls and irrigation.'),
 table('Frame rules',('Near and far ends','Inside 0 and L+1; side 0–3 at height −1 are Stable Stone.'),('End pillars','Side 0 and 3 at heights 0 and 1 are Stable Stone. The near controller replaces one corner.'),('Roof','Every row from inside 0 through L+1: side 0–3 at height 2 are Bottom Quartz Slabs.'),('Side walls','Inside 1–L: sides 0 and 3 at heights 0 and 1 are Flawless Glass.'),('Growing cells','Inside 1–L: sides 1 and 2 at height 0 above dirt/farmland.'),('Irrigation','Inside 1–L: sides 0 and 3 at height −1 start as convertible dirt/grass/farmland.')),
 block('layers','Example L=3: roof, height 2',rows=[['QQQQ']]*5,legend='Q = Bottom Quartz Slab, not a top or double slab.'),
 block('layers','Example L=3: height 1',rows=[['S..S'],['G..G'],['G..G'],['G..G'],['S..S']],legend='S Stable Stone · G Flawless Glass · dots clear'),
 block('layers','Example L=3: height 0',rows=[['C..S'],['G..G'],['G..G'],['G..G'],['S..S']],legend='Central dots in interior rows are crop positions. CO₂ Generator may replace the near right S.'),
 block('layers','Example L=3: height −1',rows=[['SSSS'],['W..W'],['W..W'],['W..W'],['SSSS']],legend='W irrigation; central interior dots need dirt/farmland underneath crops.'),
 p('Place a CO₂ Generator at side 3, inside 0, height 0, facing the same way as the controller. All fourteen greenhouse inputs can hold seeds. This tier has no automatic Build or Demolish controls.'),
 live('machine/flawless_greenhouse'),link('machines/co2_generator','CO₂ Generator and Controlled Fuel'),link('farming/growing','Farming cycle and crop tiers')
],keywords=['quartz','flawless glass','manual build','L','roof'])
add('multiblocks','dynamic','Dynamic Calculator: hollow shell',[
 p('At the shipped radius of three, build a 7×7×7 hollow cube. The controller sits in the middle of one vertical wall. The center is three blocks inside the controller at its height. The entire 5×5×5 interior must be air.'),
 p('Stable Stone forms the top/bottom perimeter and the four vertical corner pillars. Flawless Glass fills the rest of the shell, except the controller. The diagrams below show each distinct layer; repeat the indicated plain middle layer.'),
 block('layers','Bottom and top: heights −3 and +3',rows=[['SSSSSSS'],['SGGGGGS'],['SGGGGGS'],['SGGGGGS'],['SGGGGGS'],['SGGGGGS'],['SSSSSSS']],legend='S Stable Stone · G Flawless Glass'),
 block('layers','Middle layers at −2, −1, +1, +2',rows=[['SGGGGGS'],['G.....G'],['G.....G'],['G.....G'],['G.....G'],['G.....G'],['SGGGGGS']],legend='Dots must be air, not a chest, torch or decorative block.'),
 block('layers','Controller layer: height 0',rows=[['SGGCGGS'],['G.....G'],['G.....G'],['G.....G'],['G.....G'],['G.....G'],['SGGGGGS']],legend='Near wall contains C. Inside increases downward.'),
 table('Exact radius-3 shell materials',('Stable Stone',str(2*(7*7-5*5)+4*5)),('Flawless Glass',str((7**3-5**3)-(2*(7*7-5*5)+4*5)-1)),('Dynamic controller','1')),
 note('The structure radius is configurable. These counts and diagrams are for radius 3 only. Structure validation refuses unloaded targets and does not fill the cube for you.'),live('machine/dynamic_calculator'),link('machines/dynamic_calculator','Input lanes and operating behavior')
],keywords=['7x7x7','hollow cube','air inside','stable stone'])
add('multiblocks','locator','Calculator Locator: plugs and stabilizing walls',[
 p('Bind a Locator Module by using it, then insert it in the Locator. At the shipped supported radii 1–11, surround the controller with a square of Calculator Plugs. Every plug sits directly over Stable Stone. An outside Stable Stone perimeter runs around the square at heights −1 and 0; its outer corners are optional.'),
 block('layers','Radius 1 example: controller/plug level',rows=[['.SSS.'],['SKKKS'],['SKCKS'],['SKKKS'],['.SSS.']],legend='K Calculator Plug · C Locator · S perimeter wall · optional outer corners shown as dots'),
 block('layers','Radius 1 example: height −1',rows=[['.SSS.'],['SSSSS'],['SS.SS'],['SSSSS'],['.SSS.']],legend='Stable Stone beneath every plug; the center under the controller is not a plug-base requirement.'),
 p('Stable analysed boards in plugs stabilize the machine. At the default threshold of seven stable plugs the owner need not be present. Below that threshold the owner must be in the same dimension; instability can affect the owner or time, subject to server settings.'),
 p('Larger valid squares require more plugs and base blocks. Do not mistake the outer wall for another ring of plugs. A valid binding and correct structure are distinct requirements.'),
 live('machine/calculator_locator'),link('machines/calculator_locator','Locator operation'),link('machines/calculator_plug','Plug board state')
],keywords=['locator','radius','plug ring','binding','stability'])
add('multiblocks','mast','Conductor Mast and weather links',[
 p('A Conductor Mast reserves four blocks of height when placed. Upper sections belong to one controller; breaking an extension removes that structure and should return one controller, not four independent machines.'),
 block('layers','Vertical profile (top to bottom)',rows=[['M'],['M'],['M'],['C']],legend='C controller/base; M reserved mast section. This is a side view, not a floor plan.'),
 p('Weather Stations link to the nearest mast on the same height level within their configured search range. The shipped range is ten blocks. Transmitters within the shipped twenty-block range shorten the strike interval and can increase generation. Right-click a Weather Station to inspect its link.'),
 p('Generation occurs in bursts, not a perfectly constant FE/t source. Leave buffer space and sufficient cable throughput before concluding that a paused burst is a failure.'),
 live('machine/conductor_mast'),link('machines/weather_station','Weather Station'),link('machines/transmitter','Transmitter')
],keywords=['lightning','mast height','burst','weather station'])
add('farming','growing','Greenhouse growing cycle',[
 p('Greenhouses combine structure validation, irrigation, farmland preparation, planting, harvesting and optional accelerated growth. Correct material geometry alone does not guarantee that every crop can survive in every position.'),
 steps('Build or assemble the correct greenhouse tier and leave its growing cells available.','Prepare the required dirt/grass underneath the crop positions. Automatic farmland and water placement must be enabled and permitted by protection checks.','Supply seeds compatible with that tier. Basic/Advanced reserve their first four input slots for construction materials; Flawless can use all fourteen inputs for seeds.','Place a chest directly outside the controller for seed import and produce export, or use internal storage. Its side mode must allow the requested direction.','Supply FE and suitable CO₂. Watch for pending output, a disabled side, Pause, or redstone before adding more fuel.','Allow ordinary crop light/survival rules. A greenhouse does not invent a valid harvest contract for an arbitrary third-party plant.'),
 table('Native crop tiers',('Broccoli','Can also grow outside a greenhouse.'),('Prunae','Requires at least Advanced tier for greenhouse planting.'),('Fiddledew','Requires Flawless tier.')),
 p('Gas Lanterns supply CO₂ to Basic and Advanced structures; Flawless uses its correctly positioned CO₂ Generator. Carbon changes growth intervals. Planting, growth, harvest, water and farmland each have separate energy/settings controls.'),live('farming'),link('farming/compatibility','External plants and protected callbacks'),link('machines/gas_lantern_off','Gas Lantern')
],['broccoli_seeds','prunae_seeds','fiddledew_fruit'],['CO2','seeds','water','farmland','light','tier'])
add('farming','compatibility','External crops and protection-aware adapters',[
 p('Ordinary CropBlock seeds use the normal planting path and mature crop loot tables. Generic NeoForge planting support broadens acceptance, but a special crop with unusual multi-block growth or harvest behavior needs an explicit PlantAdapter.'),
 p('By default, Calculator requires an owner for protected machine world actions. Opaque external plant callbacks and sapling/tree growth are not invoked by default because checking one target cannot authorize every block an unknown callback might later modify.'),
 note('protection.allowLegacyPlantCallbacks=true is a less-protected opt-in, not a promise that a claim mod will approve every callback. Prefer a protected adapter that checks its actual affected positions. An unavailable external plant is not evidence that native greenhouse geometry is wrong.'),
 p('Preflights refuse unloaded targets, unrelated block entities and unbreakable blocks on the reviewed machine paths. Denied actions do not award Calculator harvesting drops or consume the associated construction materials. Test the actual installed protection mod before public-server use.'),live('protection'),link('troubleshooting/construction','Owner and denied-target failures')
],keywords=['TFC','TerraFirmaCraft','modded crops','PlantAdapter','claims','saplings'])
add('farming','nutrition','Nutrition modules, leaves and processors',[
 p('Hunger and health are separate stored nutrients, not FE. Matching modules collect them, processors transfer or produce them, and restoration uses the player’s current need and the module’s available contents.'),
 table('Sources and routes',('Amethyst leaves','Hunger nutrient; matching piping/logs reach a Hunger Processor.'),('Tanzanite leaves','Health nutrient; matching piping/logs reach a Health Processor.'),('Hunger Processor','Can accept food nutrition and matching module contents.'),('Health Processor','Uses its recipe-defined health sources and matching module contents.'),('Nutrition Module','Carries both nutrient types and can restore automatically while carried/installed.')),
 p('Nutrition-network traversal is bounded and checks loaded chunks. The shipped visit limit is 512 positions; this is a safety boundary, not a chunk loader. A disconnected tree or denied leaf harvest can stop collection without changing the processor inventory.'),
 link('machines/hunger_processor','Hunger Processor'),link('machines/health_processor','Health Processor'),link('machines/stone_assimilator','Stone Assimilator'),link('calculators/nutrition_module','Nutrition Module')
],['amethyst_piping','tanzanite_piping','amethyst_log','tanzanite_log','amethyst_leaves','tanzanite_leaves'],['food','healing','health','hunger','nutrition network'])
add('research','study','Research without a second progression system',[
 p('The Research Chamber studies a sample and unlocks the corresponding research group. Unlocks are stored on the server per player or in the configured server-wide shared state. Bookmarks and reading history never count as research.'),
 steps('Open Research using the button in this book to see the sample list and current unlock display.','Place a valid sample in an owned Research Chamber.','Supply the current study cost and wait through its duration. The sample is kept by default; a server option can consume it.','After completion, retry the newly unlocked calculator recipe with the correct family, counts and free result slots.'),
 p('Mastery records completed Calculator, Scientific, Atomic and Flawless batches. It is informational in this port: reaching a target does not secretly award an item or create a new recipe gate.'),
 note('Packaged guide prose is public. A reader lock icon cannot make a shipped paragraph secret. Future providers must filter genuinely restricted live information server-side rather than relying on UI hiding.'),
 live('research'),recipe('machine:research','Actual research samples and study recipes','research_chamber'),link('machines/research_chamber','Research Chamber reference')
],['research_chamber'],['unlock','sample','mastery','permission','sharing'])
add('troubleshooting','no_progress','Powered machine, no progress',[
 steps('Read the machine status. Confirm the content and machine are enabled by the server.','Remove redstone or turn off Pause unless this particular program needs a signal. The Weather Controller is an important exception: it needs a signal to act.','Check the exact recipe family, ingredient counts, circuit variant and analysis/stability requirement. A full FE bar cannot make an unmatched recipe run.','Confirm research for the machine owner, not merely a different nearby player.','Make room in every output and pending-result destination. Do not install a Void Upgrade simply to conceal blocked storage.','Compare stored FE with the full required batch cost, including overrides. Available cable throughput is not the same as enough stored energy.','For a world machine, inspect structure, owner, loaded chunks and denied-action status.','If the problem persists, keep the relevant game log and the machine/configuration details. Do not change several ratios and recipes simultaneously.'),
 link('troubleshooting/dirty_chip','A dirty or damaged chip will not process'),link('troubleshooting/blocked_output','Outputs are blocked'),link('troubleshooting/power','Energy is not transferring'),link('troubleshooting/construction','A structure or crop action is denied')
],keywords=['does nothing','not working','stuck','no recipe','redstone','paused'])
add('troubleshooting','dirty_chip','Dirty chip will not process',[
 p('A machine accepting power only proves its energy interface works. The chip still has to match a recipe in that machine’s input slots.'),
 steps('Read the item name: Dirty circuit, Damaged circuit or Circuit Board.','Use Restoration for Dirty; Reassembly for Damaged; Processing handles both. Analysis expects a clean, not already analysed board.','Put the chip in a process input, not the Power slot, an output or an upgrade slot.','Open the matching machine recipe in this guide and verify that the server still provides it.','Compare stored energy with the effective batch cost and leave output space. The progress duration can be changed in the server configuration.','After one successful batch, test automation separately so a Disabled/Input-only output face does not hide the successful conversion.'),
 recipe('machine:processing_chamber','Processing recipes','processing_chamber'),link('circuits/chain','Full circuit chain')
],keywords=['dirty','chip','damaged','cleans','repair'])
add('troubleshooting','automation','Automation that respects sides',[
 p('The Transfer Upgrade is an active exporter. External pipes pull through the exposed sided inventory. Both must respect the item-automation master setting and the face’s output mode. An Input or Disabled face is not an output face.'),
 p('Greenhouse chest import and export are separate directions on the front-facing connection. An Output-only front can export produce but cannot import seeds. An Input-only front can import seeds but cannot export produce. Auto may allow both for that program.'),
 steps('Manually complete one batch with empty output slots.','Set the desired face to Output and connect an inventory whose facing side accepts the result.','Check machine.<id>.itemAutomation and the Transfer Upgrade’s actual presence/count.','Remove input-only or Disabled faces from the export route.','Fill the destination deliberately and verify that products remain pending rather than disappearing.','Change the side back and retest. A pipe’s own filter, channel, or extraction rule can still refuse the item.'),
 note('Energy ports are governed by energy side and adapter policies, not just item-automation switches. Test the item and energy routes separately.'),link('power/routing','Energy routing'),link('troubleshooting/blocked_output','Pending results and Void Upgrade')
],['transfer_upgrade'],['pipe','sided','input','output','disabled','master switch'])
add('troubleshooting','blocked_output','Blocked outputs, retention and deliberate voiding',[
 p('Completed results are retained when ordinary output storage is full. The machine can pause with a finished batch waiting, even when power and input look correct. Drain the destination before expecting another batch.'),
 p('The Void Upgrade explicitly permits disposal of completed results that do not fit. It is not a performance upgrade or a required part of automation. Leave it out when lossless storage is important.'),
 p('Configured capacity reductions preserve existing excess contents rather than deleting them immediately. A previously full buffer may therefore exceed a newly lowered capacity until energy or items are withdrawn.'),
 steps('Open the target inventory and verify actual free space for the exact item/components.','Check output side mode and receiver insertion rules.','Remove or account for any Void Upgrade.','Drain the blockage and confirm processing resumes.','For save/restart testing, use a copy of the world and compare exact counts before and after.'),
 link('calculators/upgrades','Upgrade behavior'),link('troubleshooting/dismantling','Moving machines safely')
],['void_upgrade'],['overflow','full chest','lost output','pending','void'])
add('troubleshooting','power','Connected cable, no energy transfer',[
 steps('Identify which API the actual route uses: FE, GT EU, Mekanism J, MI EU, GrandPower or an item-only adapter.','Check both the local face and the source/receiver face. Input/output terminology is relative to the Foundations buffer.','Verify the appropriate blockPorts or itemCharging scope, input/output gate, old compat master toggle and GT direction toggle.','Read the effective ratio and losses. An offer smaller than the conversion quantum cannot be rounded up.','For GT, check voltage, amperage, shared tick budget, battery tier and loss-adjusted packet cost.','Make space in the receiving buffer and test with a source that actually has stored power.','Use the Power button or /foundations power inspect while looking at a machine. Reports simulate readiness; they do not transfer energy or force-load chunks.'),
 note('A disabled native-first adapter does not silently fall back to FE. A third-party source can still choose its own FE path if Calculator advertises it. This is a route-selection distinction, not a reason to add free conversion multipliers.'),live('power'),link('power/rounding','Transfer quanta and conservative rounding')
],keywords=['no energy','power','cable','cannot charge','battery','voltage'])
add('troubleshooting','construction','Build, harvest or planting stopped',[
 steps('Confirm the machine has a valid owner and the actual target positions are loaded.','Read denied-world-action status. Ask an authorized owner/admin to resolve permission, rather than disabling protection as the first fix.','Check the entire construction bounds, including roofs, overhangs and below-ground layers.','Refill the correct construction input: logs, stairs, glass, planks. Seeds do not replace a missing wall material.','Supply energy for each placement, farmland/water action or harvest.','For a manual structure, compare each layer and orientation; it has no automatic Build action.','For a modded crop or sapling, check whether its protected PlantAdapter exists. Legacy callback support is intentionally off by default.','Check pending outputs before Demolish or harvest; completed recovery must have somewhere to go.'),
 live('protection'),link('multiblocks/coordinates','Controller-relative plans'),link('farming/compatibility','Third-party crop boundaries')
],keywords=['build failed','claim','owner','demolish','unloaded','obstruction'])
add('troubleshooting','dismantling','Moving machines without losing their contents',[
 p('Use the wrench deliberately. A normal face use cycles side modes. Sneak-use dismantles a supported machine while preserving its inventory, FE and settings when the relevant preservation options are enabled.'),
 steps('Stop input automation and let the current batch finish or pause it.','Check pending results and external connections.','Sneak-use the wrench and confirm that exactly one machine item was returned.','Place it again and compare inventory, charge, side settings and module contents.','Recheck owner/protection status at the new site before restarting world-changing actions.'),
 p('Breaking a multi-block machine extension removes the owning controller structure rather than creating independent copies of each section. When testing a new release, use a copied world before moving valuable machinery.'),
 recipe('item:'+NS+'wrench','Obtain the wrench'),link('troubleshooting/automation','Reconnect sided automation')
],['wrench'],['pick up','move','dismantle','retain','backup'])
add('calculators','upgrades','Speed, energy, transfer and void upgrades',[
 table('Choose the right behavior',('Speed Upgrade','Reduces the ordinary processor duration according to the configured bonus.'),('Energy Upgrade','Reduces eligible process cost according to the configured discount.'),('Transfer Upgrade','Actively exports finished items through permitted output faces.'),('Void Upgrade','Explicitly discards completed overflow when enabled. This is intentionally lossy.')),
 p('Special machine programs can have their own timing and energy rules; a visible upgrade slot does not mean every world action uses the ordinary process formula. The recipe reader labels its baseline calculations as before installed upgrades.'),
 p('Transfer throughput scales with upgrade count up to its configured cap. In the shipped settings each Transfer Upgrade contributes four items per transfer, with a cap of 64. These are defaults, not a substitute for the server configuration.'),
 recipe('item:'+NS+'speed_upgrade','Obtain Speed Upgrades'),recipe('item:'+NS+'energy_upgrade','Obtain Energy Upgrades'),link('troubleshooting/automation','Transfer directions'),link('troubleshooting/blocked_output','Void and blocked output')
],['speed_upgrade','energy_upgrade'],['upgrade','speed','efficiency'])
# Fully individual machine purpose, operation sequence and failure diagnosis.
machines={
'power_cube':('Small FE buffer with a Discharge input and Charge output. Its charge rate is deliberately separate from its cable transfer rate.', ['Feed FE from a permitted input face or discharge a supported battery/consumable.','Put a powered item in Charge to transfer energy out of the cube.','Connect output faces to machines and verify both side and adapter policies.'], 'A slowly charging item may be limited by the configured item charge rate, not by the cube capacity. Empty FE or a full receiver also pauses charging.'),
'advanced_power_cube':('A higher-tier FE buffer and item charger. It keeps the same distinction between storage, cable throughput and item-charging throughput.', ['Supply power through a valid input or discharge slot.','Place the target battery or tool in Charge.','Set faces deliberately before attaching mixed EU/J/FE connections.'], 'The external item can impose its own tier, direction, capacity or transfer limit even when the cube has room and power.'),
'creative_power_cube':('Creative/testing power supply. It replenishes stored FE; it is not intended as a survival progression reward.', ['Place it in a test world.','Enable a permitted output face.','Use it to isolate receiver-side problems, then retest with a finite survival source.'], 'Do not treat a test with an unlimited source as proof that your normal generator can meet the required throughput.'),
'atomic_calculator':('Placed three-input Atomic calculation. It uses the atomic recipe family and ordinary server process overrides.', ['Open an Atomic recipe and collect all three input requirements.','Put them in the machine input area and supply power if required.','Leave the result area free and verify the owner’s research access.'], 'A Basic or Scientific recipe will not match simply because its ingredients fit the available slots.'),
'dynamic_calculator':('Runs Basic, Scientific and Atomic lanes in one validated hollow shell. The lanes share output storage, rather than maintaining three independent output inventories.', ['Build the controller-relative shell described in Multiblocks.','Put Basic inputs in positions 1–2, Scientific in 3–4, Atomic in 5–7.','Supply FE and keep shared outputs clear.','Wait for the scheduled structure check after correcting a missing wall.'], 'An occupied interior, wrong corner material, unloaded shell position or blocked shared output can stop all lanes.'),
'module_workstation':('Edits modules inside a Flawless Calculator. Removing the calculator takes its installed contents with it.', ['Insert the Flawless Calculator in its labelled slot.','Install supported modules into the module slots.','Remove it and sneak-use it to choose an installed action.'], 'Atomic Module and ordinary assembly ingredients are not automatically usable modules. See the installation chapter for accepted categories.'),
'reinforced_furnace':('Electric furnace using current furnace-smelting recipes, not fuel burn time as its FE cost. It retains returned containers and completed outputs.', ['Place a smeltable item in the input.','Provide enough FE for the configured furnace batch.','Leave room for the output and any crafting remainder.'], 'The furnace’s process cost/time are machine settings; they are not the same as an ingredient’s furnace fuel value.'),
'reinforced_chest':('General storage with an animated lid and viewer tracking. It does not need power to store items.', ['Open it and insert items.','Connect permitted item automation as needed.','Close the menu before testing dismantling or viewer animation.'], 'This is not the bulk-bin Storage Chamber. Lid appearance is a client setting and does not change item ownership.'),
'stone_separator':('Separates configured stone, wood and other basic materials into useful products. One input can produce multiple outputs.', ['Choose a live Stone Separator recipe.','Supply its exact ingredient and full batch energy.','Reserve space for every output, including secondary products such as sticks or shards.'], 'An empty secondary output destination can matter as much as the primary one; check all pending results.'),
'algorithm_separator':('Higher-value separation recipes, including configured gem and redstone transformations. Its recipe family is distinct from the Stone Separator.', ['Read the exact accepted tag or item in the recipe card.','Supply the configured process energy.','Collect every result and preserve any components required by later stages.'], 'A Stone Separator recipe is not valid here unless the server explicitly adds it to this machine family.'),
'hunger_processor':('Collects hunger nutrient from matching modules, supported food values and a matching nutrition network; fills an appropriate destination module.', ['Supply food or a module with hunger in the input role.','Put the destination Hunger/Nutrition Module in the special module slot.','Connect mature Amethyst leaves through matching piping/logs for world collection.'], 'FE is not the stored hunger quantity. A full module, exhausted food source or denied leaf harvest can pause transfer.'),
'health_processor':('Collects recipe-defined health nutrient or existing health-module contents and fills a destination module. Matching Tanzanite networks can supply leaf nutrient.', ['Inspect the current Health Processor value recipes.','Place the destination Health/Nutrition Module in its module slot.','Connect compatible leaves and keep the traversal loaded and permitted.'], 'Not every edible item is a health source. The health program uses its own value recipes.'),
'docking_station':('Automates the recipe family of a calculator inserted in its special slot.', ['Insert Basic, Scientific, Atomic or Flawless Calculator in the calculator slot.','Supply that device’s required ingredients in the inputs.','Provide the docking batch energy and output room.'], 'With no recognized calculator installed, the recipe family is none. A charged device alone does not replace the station’s machine energy.'),
'atomic_multiplier':('Duplicates eligible stackable input using circuit boards and a large FE batch. The blacklist excludes protected progression items.', ['Put one eligible stackable item and seven circuit boards in the first eight input slots.','Accumulate the current full batch cost; the default is 1.5 billion FE.','Leave room for four copies and let the batch complete.'], 'Unstackable or blacklisted items are refused. Increasing cable voltage does not bypass the item blacklist or the FE requirement.'),
'extraction_chamber':('Turns dirt/cobblestone into Soil/Small Stone and can find dirty or damaged circuits. It produces raw circuits, not analysed boards.', ['Choose dirt or cobblestone according to the recipe.','Supply the complete batch cost and wait through the duration.','Separate guaranteed material output from chance-based circuit output.'], 'Not receiving a chip on every cycle is expected for chance results. Use Precision recipes when you need a more specific route.'),
'restoration_chamber':('Cleans dirty circuits into matching clean board variants.', ['Insert a Dirty circuit in an input slot.','Supply its process cost and leave output room.','Send the resulting board to analysis when a later use requires analysed state.'], 'Damaged circuits belong in Reassembly or Processing, not this cleaning-only path.'),
'reassembly_chamber':('Repairs damaged circuits into their matching clean boards.', ['Insert a Damaged circuit, not a clean board.','Supply the process energy and duration.','Collect the board and analyse it for state-dependent uses.'], 'Dirty circuits belong in Restoration or Processing.'),
'precision_chamber':('Provides configured precision extraction routes, including specific block-to-circuit results alongside small-stone output.', ['Read the recipe for the exact desired circuit variant.','Provide the specified source block/tag.','Supply FE and collect both ordinary and circuit results.'], 'Some recipes choose a random variant while others specify a particular chip. The live output card identifies random-circuit results.'),
'processing_chamber':('Combines dirty-circuit cleaning and damaged-circuit repair in one machine.', ['Place a Dirty or Damaged circuit in the process input.','Check that the corresponding server recipe is present.','Provide full batch energy and clear output slots.','Move the resulting clean board into the analyser.'], 'A clean/already analysed board is not the dirty/damaged input this chamber expects.'),
'analysing_chamber':('Analyses clean circuit boards, reveals stability, returns the analysed board and can award recipe-driven items or FE.', ['Clean or repair the raw chip first.','Insert the unanalysed clean board.','Leave room for the board and additional rewards.','Read the returned board tooltip before fabrication or plug use.'], 'Already analysed boards do not run again. The analyser can also export generated/reward energy, subject to its sides.'),
'storage_chamber':('Bulk item storage with per-bin quantities and representative stacks rather than an ordinary chest grid.', ['Open the bulk-storage screen.','Insert an item into its intended bin and read the stored quantity.','Withdraw a test stack and verify the remaining total before connecting automation.'], 'A full or filtered bin can refuse a different item/component set even when another bin is empty. Capacity decreases preserve existing excess contents.'),
'fabrication_chamber':('Builds configured devices and upgrades from exact combinations of analysed circuit boards.', ['Use the recipe card to identify board numbers and state requirements.','Analyse required boards before insertion.','Provide FE and keep the finished-device output free.'], 'A board with the right number but no analysed state cannot satisfy an analysed ingredient.'),
'basic_greenhouse':('Automatically constructed starter greenhouse with eight growing cells around central water.', ['Load logs, stairs, glass and planks into its first four inputs, then press Build.','Prepare dirt/grass beneath the growing area and supply compatible seeds.','Use a Gas Lantern for carbon and an outside chest for permitted seed/produce automation.'], 'Its roof is wider than the crop area. Wrong construction-slot order, missing energy, denied targets or higher-tier seeds can stall it.'),
'advanced_greenhouse':('Larger automatically constructed greenhouse with 45 growing positions and four irrigation corners.', ['Clear the full roof and foundation bounds.','Supply the four construction materials in order and use Build.','Plant compatible seeds, including Prunae, and manage CO₂ with a lantern.'], 'Fiddledew still needs Flawless tier. An enlarged greenhouse does not bypass protection or ordinary crop survival rules.'),
'flawless_greenhouse':('Manual four-wide greenhouse with configurable interior length and two central crop columns.', ['Assemble Stable Stone ends, Flawless Glass walls and Bottom Quartz Slab roof.','Put the CO₂ Generator at the correct near corner with matching facing.','Use all fourteen seed inputs and supply FE.'], 'It has no automatic Build or Demolish controls. Wrong slab half, a missing end pillar or an over-limit length invalidates the layout.'),
'co2_generator':('Supplies carbon to a correctly aligned Flawless Greenhouse by burning fuel and consuming FE per fuel item.', ['Place it three blocks to the specified side of the Flawless controller, same facing.','Provide a valid fuel and enough FE for the entire fuel start.','Use Controlled Fuel for the configured high-carbon pause/resume behavior.'], 'At the shipped values Controlled Fuel pauses at 100% and resumes at 92%, preserving paused burn time. Wrong position/facing prevents the intended link.'),
'calculator_locator':('Owner-bound FE generator whose plug platform and stable boards determine valid operation and instability.', ['Bind and insert a Locator Module.','Build the square of plugs, base blocks and outside wall.','Insert stable analysed boards in plugs.','Provide output space or a battery to receive generated energy.'], 'Below the stabilization threshold the owner must be nearby in the same dimension. A bound module is not a replacement for a valid structure.'),
'calculator_plug':('Holds a circuit board to contribute stability to a Locator platform.', ['Place the plug at controller height on Stable Stone.','Insert a stable analysed board.','Read the active state and recheck the surrounding Locator square.'], 'A dirty chip or unanalysed/unstable board is not a stabilizing board. Plugs are not generic FE storage blocks.'),
'conductor_mast':('Tall generator with burst-based lightning output and linked Weather Stations/Transmitters.', ['Leave the reserved vertical height clear.','Place stations at the same height within their configured range.','Provide buffer space and a permitted output route.'], 'Output is burst-based. A full buffer or slow connection can make the mast appear idle between strikes.'),
'weather_station':('Links to a nearby Conductor Mast and increases its generation behavior.', ['Place it on the same level as a mast within the configured search distance.','Right-click to inspect the linked mast.','Wait through the mast’s burst/strike schedule when testing.'], 'A closer mast can become the chosen link; distance and level are part of discovery, not just visual proximity.'),
'transmitter':('A nearby Conductor Mast support block affecting strike intervals and output.', ['Place within the configured mast range.','Pair with a valid mast setup.','Measure complete burst cycles rather than one isolated tick.'], 'It is not a wireless item pipe or a standalone FE generator; its role belongs to the mast program.'),
'starch_extractor':('Consumes recipe-defined nutrient and furnace fuel to produce FE over the fuel’s burn time.', ['Put valid furnace fuel in the first input.','Put an accepted starch-value ingredient in the second input.','Accumulate enough nutrient for a fuel start, then export FE.'], 'Fuel alone is insufficient if the nutrient reservoir is below its configured start cost.'),
'redstone_extractor':('Uses its redstone nutrient-value recipes and ordinary furnace fuel for ongoing FE generation.', ['Supply fuel in input one.','Supply a redstone-value ingredient in input two.','Set an output side and monitor the nutrient reservoir.'], 'An item accepted by the Starch Extractor is not automatically a valid redstone-value ingredient.'),
'glowstone_extractor':('Uses its glowstone-value ingredient family plus furnace fuel to generate FE.', ['Provide valid furnace fuel.','Provide an ingredient shown in this extractor’s value recipes.','Keep a receiving buffer available.'], 'Nutrient and burn time are separate resources. A zero nutrient input cannot be repaired by increasing the EU conversion rate.'),
'hand_cranked_generator':('Manual FE source for starting or testing a small workshop.', ['Place the generator and use its crank interaction.','Connect a permitted energy output to your first buffer or machine.','Repeat until the full intended process batch is funded.'], 'A large late-game recipe can require far more FE than repeated cranking is convenient for. The server can change energy per use.'),
'crank_handle':('Auxiliary crank component associated with the hand-powered setup.', ['Use the current recipe to obtain the part when needed.','Install/use it in the generator’s intended setup rather than expecting a processing inventory.','Read the generator page for FE behavior.'], 'The handle is not a general processor and has no separate normal recipe-processing cycle.'),
'magnetic_flux':('Collects nearby item entities into the inventory directly below it using an eight-slot filter.', ['Put representative items in filter slots.','Choose whitelist/blacklist and item/tag versus component matching.','Place a receiving inventory underneath and remove a disabling redstone signal.'], 'An entity remains in the world when transfer is blocked. Filter mode, range or a full inventory can explain no collection.'),
'weather_controller':('Changes Time, Rain or Thunder after its powered/redstone-driven operation completes.', ['Choose the mode and desired state.','Supply FE and a redstone signal.','Maintain power through the configured operating duration, then allow its cooldown.'], 'Unlike many ordinary machines, no redstone signal means no operation. If the world already has the target state, another change may be unnecessary.'),
'rain_sensor':('Emits redstone strength 15 while the world is raining.', ['Place the sensor and connect redstone.','Compare the output during dry and rainy weather.','Use it as a signal, not as an inventory-based processor.'], 'Local visual shelter does not create a separate per-block rainfall state for this sensor.'),
'stone_assimilator':('Collects health or hunger from mature Calculator-tree leaves into a matching module.', ['Place beside a three-block trunk, facing away from it.','Provide at least the required nearby leaf count.','Insert a module with matching nutrient capacity and allow leaf maturity.'], 'Wrong trunk orientation, insufficient mature leaves, a full module or denied world actions can stop collection.'),
'algorithm_assimilator':('Collects pear/diamond tree products into its bulk bins when its adjacent tree satisfies the program.', ['Place beside the three-block trunk, facing away.','Maintain a valid tree with the required leaf count.','Let leaves mature and withdraw products from the bins.'], 'This collects configured tree products, not arbitrary drops from any modded tree.'),
'gas_lantern_off':('Fuel-burning light source that contributes carbon to Basic/Advanced Greenhouses.', ['Put ordinary furnace fuel in the lantern.','Place it within the greenhouse’s eligible space.','Keep it burning and observe greenhouse carbon over time.'], 'The item’s registry ID says off because active state controls its lighting. A spent lantern cannot provide ongoing carbon.'),
'scarecrow':('Periodically attempts accelerated growth on a nearby eligible plant.', ['Place it within the configured range of crops.','Allow the growth interval to elapse.','Check plant eligibility, maturity and the protected-callback policy.'], 'One interval attempts a bounded growth action; it does not instantly grow every plant in the area.'),
'calculator_screen_block':('Mounted energy display for the adjacent face of an FE-compatible block.', ['Use the Calculator Screen item on a horizontal face of an energy block.','Read that face’s stored energy and capacity.','Recheck the target capability when rotating or replacing the block.'], 'This is a display, not a battery, converter or power cable.'),
'research_chamber':('Studies a sample and unlocks its category for the owner or configured shared research state.', ['Place the chamber with a valid owner.','Insert a sample listed in Research.','Supply study energy and wait for completion.','Read the unlock message and retry the newly available recipe.'], 'A sample for an already unlocked group will not repeatedly create rewards. Sample consumption is a separate server option.')
}
source=(P/'src/main/java/com/foundations/calculator/content/Content.java').read_text()
actual=re.findall(r'addBlock\("([^"]+)"[^\n]*true,false',source)
assert set(actual)==set(machines),(set(actual)-set(machines),set(machines)-set(actual))
lang=json.loads((P/'src/main/resources/assets/foundations_calculator/lang/en_us.json').read_text())
configs=json.loads((P/'src/main/resources/foundations/configuration.json').read_text());configkeys={v['key'] for v in configs}
family_counts=collections.Counter()
for f in (P/'src/main/resources/data/foundations_calculator/recipe').rglob('*.json'):
 r=json.loads(f.read_text());family_counts[r.get('machine','')]+=1
for id,(purpose,seq,fail) in machines.items():
 name=lang.get('block.foundations_calculator.'+id,id.replace('_',' ').title())
 b=[h('Purpose'),p(purpose),h('Set up and operate'),steps(*seq),h('When it does not run'),p(fail)]
 if id not in ['rain_sensor','crank_handle','transmitter','weather_station','calculator_screen_block','reinforced_chest']:b+=[p('Read the active server settings below before copying default costs from another installation. For special slot roles, use the machine screen labels. Settings reporting does not inspect or mutate a placed machine.')]
 b += [live('machine/'+id)]
 query_family={'atomic_calculator':'atomic','research_chamber':'research'}.get(id,id)
 if family_counts[query_family]:b += [recipe('machine:'+query_family,'Processing / value recipes',profile=id)]
 if id not in ['calculator_screen_block']:b += [recipe('item:'+NS+id,'Crafting / obtaining this machine')]
 if id in ['basic_greenhouse','advanced_greenhouse','flawless_greenhouse']:b += [link('multiblocks/'+id,'Construction plans and layers')]
 elif id=='dynamic_calculator':b += [link('multiblocks/dynamic','Exact default shell layers')]
 elif id=='calculator_locator':b += [link('multiblocks/locator','Locator platform diagram')]
 elif id=='conductor_mast':b += [link('multiblocks/mast','Mast and station placement')]
 else:b += [link('troubleshooting/no_progress','General operating checklist')]
 add('machines',id,name,b,['calculator_screen' if id=='calculator_screen_block' else id],keywords=[id,purpose.split('.')[0][:128]])
module_info={
 'storage_module':('Stores a carried inventory. When installed, its contents remain part of the Flawless Calculator component.','Open it, place items, close it, and check the same contents after selecting another module. It cannot be nested indiscriminately inside container items.'),
 'warp_module':('Binds a destination and teleports you there subject to energy, clearance, dimension and loading restrictions.','Sneak-use a permitted stable block to bind. Use the module normally to warp. By default the destination must be loaded and in the same dimension; two empty blocks above the bound position are required.'),
 'jump_module':('Applies an upward movement impulse using FE.','Charge the module or carrying calculator, then use it. Velocity and cooldown are server settings. An empty battery cannot perform the jump.'),
 'hunger_module':('Stores hunger nutrient for restoration, rather than storing hunger as FE.','Fill it through matching mature leaves or a Hunger Processor. Use it to restore available hunger; check both player need and stored nutrient.'),
 'health_module':('Stores health nutrient for restoration.','Fill from matching Tanzanite leaves or a Health Processor. Use it to restore health from available contents.'),
 'nutrition_module':('Combines health and hunger storage and can restore automatically while carried or installed.','Fill each nutrient type through its matching source. Watch the respective quantities; one nutrient cannot substitute for the other.'),
 'terrain_module':('Cycles among the basic grass/dirt/stone terrain choices.','Sneak-use to choose the replacement from the supported list, then use on a matching convertible material. The ordinary terrain module is a bounded material-conversion tool, not the unrestricted Atomic Terrain selector.'),
 'advanced_terrain_module':('Extends the ordinary terrain choices with gravel, sand and cobblestone.','Sneak-use to cycle the supported replacement, then use on an accepted source. Costs are configurable; unsupported blocks are not transformed.'),
 'atomic_terrain_module':('Stores a source and replacement selection for permission-checked block exchange.','Sneak-use the source block, then sneak-use the replacement. Use on the selected source material to exchange it. Carry replacement blocks when required; containers, unbreakable blocks and blacklist entries are refused.'),
 'energy_module':('Adds FE storage, including additional storage when installed in a Flawless Calculator.','Charge it through a compatible charger. Use it to read stored energy. Extra storage is not an energy generator and does not override a charger’s rate or native tier.'),
 'locator_module':('Binds its owner identity for a Calculator Locator.','Use it to bind yourself, then place it in the Locator’s module slot. The book does not display the raw owner UUID or allow binding to another player.'),
 'smelting_module':('Portable electric smelting with inputs, outputs and a Returns area for empty containers.','Put in a smeltable input and charge the module/carrier. Processing can continue while carried or installed when the server enables background processing. Full outputs or insufficient energy pause safely.'),
 'crafting_calculator':('Opens a portable crafting grid using the configured FE activation cost.','Charge it, use it and craft with the current server’s crafting recipes. This is not a new process family and does not ignore ordinary crafting requirements.')
}
for id,(purpose,use) in module_info.items():
 b=[h('Purpose'),p(purpose),h('Use'),p(use),link('calculators/installing','Using modules inside a Flawless Calculator')]
 if any(k.startswith('module.'+id+'.') for k in configkeys):b += [live('module/'+id)]
 b+=[recipe('item:'+NS+id,'Obtain this module')]
 add('calculators',id,lang.get('item.foundations_calculator.'+id,id.replace('_',' ').title()),b,[id],keywords=['module',id])
add('calculators','materials','Crafting components, tools and decorative materials',[
 p('Calculator Assembly, Advanced Assembly and Atomic Module are progression crafting components. Similar names do not mean they open their own usable module screen. Use their live recipe references to distinguish ingredients from installed tools.'),
 recipe('item:'+NS+'calculator_assembly','Calculator Assembly'),recipe('item:'+NS+'advanced_assembly','Advanced Assembly'),recipe('uses:'+NS+'atomic_module','Uses for Atomic Module'),
 p('Material families include stable stone, reinforced materials, gems/shards, redstone/enriched-gold ingredients, Calculator trees, and decorative Sonar Core blocks. Their crafting links remain data-driven. Search a specific item ID to find its group, then use the recipe links supplied in that group.'),
 p('Tools such as the Sickle and Obsidian Key perform their dedicated block interactions. The reusable End Diamond throws an ender-pearl-like projectile while retaining the item. Tool durability, cooldowns and material properties are independently configurable.'),
 recipe('item:'+NS+'end_diamond','Reusable End Diamond'),recipe('item:'+NS+'sickle','Sickle'),recipe('item:'+NS+'obsidian_key','Obsidian Key')
],['calculator_assembly','advanced_assembly','atomic_module','end_diamond','sickle','obsidian_key'],['crafting components','assembly','tools'])
add('pack_authors','configuration','Configuration and scripting reference',[
 p('Gameplay settings belong to foundations_calculator-server.toml in the world’s serverconfig location. Pack defaults can be distributed through defaultconfigs. Client appearance uses the client configuration; client edits cannot replace server rules.'),
 p('For a repeatable configuration change, stop the server, edit the intended existing TOML key, and restart. /reload reloads data packs; it is not a universal TOML reload command. Programmatic changes should use the validated settings API and its change notification.'),
 table('Customization surfaces',('Per-content / per-machine','Enable entries, capacities, automation, transfer, energy, time and special behaviors.'),('Per-recipe','Enable recipes, override energy/time and adjust result chance multipliers.'),('Data packs','Replace or add actual process recipe definitions.'),('KubeJS','Optional recipe schema/raw recipe JSON; see examples/kubejs in source.'),('CraftTweaker','Optional add/addJson/remove/removeMachine API; see source examples.'),('Client resource packs','Replace guide book/chapter/entry JSON and illustration resources.')),
 note('Do not paste duplicate TOML tables or duplicate JSON object keys. Invalid guide packages are rejected with bounded diagnostics instead of being executed. Guide pages cannot run commands, read arbitrary files, or name Java classes.'),
 p('Server recipe values and unlocks are not hidden solely because a guide page is marked unavailable. Server authority belongs to the gameplay service and bounded snapshot provider.'),
 h('0.0.2a scale and balance'),p('Long-valued capacity multipliers are separate from conversion ratios. Use energy.machineCapacityMultiplier, energy.itemCapacityMultiplier and energy.transferMultiplier for pack-wide scale, then per-machine/module capacityMultiplier keys for exceptions.'),p('Presets are opt-in. balance.applyPreset=false preserves explicit R9 behavior. When enabled, balance.preset selects 1 Classic, 2 Balanced, 3 Expert or 4 High Power. /foundations config presets prints the exact effects without changing the file.'),p('Operators can use /foundations config machine <id> for derived machine totals, /foundations config get <key> for synchronized configured values, and /foundations config find <text> to locate settings. These commands require operator permission and never change the configuration.'),link('power/scaling','Long buffers, units & scale'),
 link('pack_authors/publishing','Publish a compatible guide'),link('power/eu_conversion','Conversion configuration')
],keywords=['KubeJS','CraftTweaker','datapack','TOML','serverconfig','reload'])
add('pack_authors','publishing','Publishing to the future master guide',[
 p('The portable Guide API separates descriptor/content from rendering and live values. Calculator’s standalone reader and any compatible master host consume the same immutable books, chapters, entries and structured page blocks.'),
 table('Static resource layout',('Manifest','assets/<owner>/foundations_guides/<book>/book.json'),('Chapter','chapters/<name>.json referenced by the manifest'),('Entry','entries/<path>.json referenced by the manifest'),('Guide identity','Namespaced and stable, for example foundations_calculator:field_guide.'),('Entry identity','Stable namespaced target, independent of screen class or page number.')),
 p('Static guides require no Java dependency on Calculator. A publisher places valid resources in its own namespace, declares its owner/required mods, and uses contract schema 1. Unknown extensions require a useful text fallback; unsupported schema versions are diagnosed.'),
 p('Java hosts and live providers use the small shared com.foundations:foundations-guide-api artifact. It is an embedded, version-selected library—not a separate required Core mod. Do not copy its classes into each mod or shade/relocate them. The SDK documents the shared Jar-in-Jar coordinates.'),
 p('A host declares API version, page capabilities and acceptance, then opens an exact guide/entry target inside its reader. No positive acceptance means standalone fallback. Reading does not require all source items and never grants research. If the host is removed, existing source books remain usable.'),
 note('0.0.2a retains the contract and development fixture, not the finished master-guide mod. Unrelated third-party books need explicit adapters. No automatic parsing of arbitrary external screens is claimed.'),
 p('The SDK and schema examples are included in the source release. Use the development second-guide fixture to test discovery, resource reload, cross-guide links, host acceptance and fallback before publishing another provider.')
],keywords=['API','master guide','federation','provider','SDK','resource pack','Jar-in-Jar'])
# Add searchable grouped material entries for every remaining inventory registry ID, with live recipe cycling.
registry=json.loads((P/'tools/content_catalog.json').read_text())
known={i for e in entries for i in e['items']}
remaining=[x for x in registry if NS+x['id'] not in known and x['id'] not in {'machine_extension','crop_broccoli','crop_prunae','crop_fiddledew'}]
groups=collections.defaultdict(list)
for x in remaining:
 id=x['id'];group='Decorative blocks' if any(s in id for s in ['stone','glass','stained','reinforced','fence','stairs','slab']) and x['kind']=='block' else 'Tree and crop products' if any(s in id for s in ['pear','diamond_tree','broccoli','prunae','fiddledew','sapling','leaves','log','planks','wood']) else 'Materials and equipment'
 groups[group].append(id)
for group,ids in groups.items():
 # 12 records per page avoids bloated documents and preserves all item/recipe links.
 for start in range(0,len(ids),12):
  subset=ids[start:start+12];b=[p('This reference groups related inventory entries. Each recipe section reads the current world. An item may have no crafting result when it comes from harvesting, world generation, a program action or creative tools.')]
  for id in subset:b += [item(id),recipe('item:'+NS+id,'Obtaining '+lang.get('item.foundations_calculator.'+id,lang.get('block.foundations_calculator.'+id,id.replace('_',' '))))]
  add('pack_authors',group.lower().replace(' ','_')+'_'+str(start//12+1),group+' · '+str(start//12+1),b,subset)
# Cross-references for all deep links must exist.
ids={e['id'] for e in entries}
for e in entries:
 for b in e['blocks']:
  if b['type']=='link':assert b['target'] in ids,(e['id'],b)
R.mkdir(parents=True,exist_ok=True)
for i,(id,title) in enumerate(chapters):
 f=R/'chapters'/f'{id}.json';f.parent.mkdir(exist_ok=True);f.write_text(json.dumps({'id':NS+id,'title':title,'order':i},indent=2,ensure_ascii=False)+'\n')
for e in entries:
 rel=e['id'].split(':',1)[1];f=R/'entries'/f'{rel}.json';f.parent.mkdir(parents=True,exist_ok=True);f.write_text(json.dumps(e,indent=2,ensure_ascii=False)+'\n')
manifest={'schema':1,'id':NS+'field_guide','owner':'foundations_calculator','title':'Calculator Field Guide','icon':NS+'info_calculator','revision':re.search(r'^mod_version=(.+)$',(P/'gradle.properties').read_text(),re.M)[1],'landing':NS+'getting_started/welcome','chapters':[f'chapters/{id}.json' for id,_ in chapters],'entries':['entries/'+e['id'].split(':',1)[1]+'.json' for e in entries]}
(R/'book.json').write_text(json.dumps(manifest,indent=2)+'\n')
report={'chapters':len(chapters),'entries':len(entries),'machine_entries':len(machines),'module_entries':len(module_info),'item_links':len({i for e in entries for i in e['items']}),'word_count':sum(len(b.get('text','').split())+sum(len(' '.join(r).split()) for r in b.get('rows',[])) for e in entries for b in e['blocks']),'blueprint_counts':{str(t):dict(collections.Counter(d.values())) for t,d in by.items()},'source':'Current production programs, recipes, configuration catalog and MULTIBLOCKS.md; greenhouse maps exported from production GreenhouseBlueprint using isolated coordinate fixtures, not Minecraft runtime'}
(P/'docs/guide/CONTENT_COVERAGE.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
import subprocess,sys
subprocess.run([sys.executable,str(P/'tools/generate_patchouli_bridge.py')],check=True)
