"""Translate upstream Techne cuboids into Mojang ModelPart definitions, preserving UVs and rotations."""
from pathlib import Path
import re,json
R=Path(__file__).resolve().parents[1];root=R.parent/'upstream-calculator/src/main/java/sonar/calculator/mod/client/models'
models=['Chamber','Processing','Split','ConductorMast','Transmitter','Scarecrow','DockingStation','CrankHandle','WeatherStationBase','WeatherStationDish','FabricationArm','MagneticFlux']
lines=['package com.foundations.calculator.client;','import net.minecraft.client.model.geom.*;','import net.minecraft.client.model.geom.builders.*;','/** Upstream Calculator Techne meshes, MIT copyright Ollie Lansdell. Generated by tools/import_legacy_models.py. */','public final class LegacyModels {']
report={}
def floats(args):return ','.join(str(float(x.strip().rstrip('fF')))+'f' for x in args.split(','))
for model in models:
 s=(root/f'Model{model}.java').read_text();s=re.sub(r'/\*.*?\*/','',s,flags=re.S);s=re.sub(r'//[^\n]*','',s)
 names=re.findall(r'(\w+)\s*=\s*new ModelRenderer\(this,\s*(\d+),\s*(\d+)\)',s)
 lines.append(f' public static ModelPart {model[0].lower()+model[1:]}(){{MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();')
 for name,u,v in names:
  boxes=re.findall(r'\b'+name+r'\.addBox\(([^)]+)\)',s);assert boxes,(model,name)
  position=re.search(r'\b'+name+r'\.setRotationPoint\(([^)]+)\)',s);rot=re.search(r'setRotation\('+name+r',\s*([^)]+)\)',s)
  cube=f'CubeListBuilder.create().texOffs({u},{v})'
  # set mirror comes after addBox in old Techne; cubes were created before the flag changes.
  for box in boxes:assert len(box.split(','))==6,(model,name,box);cube+='.addBox('+floats(box)+')'
  pose=floats(position[1] if position else '0,0,0')+','+floats(rot[1] if rot else '0,0,0')
  lines.append(f' root.addOrReplaceChild("{name}",{cube},PartPose.offsetAndRotation({pose}));')
 width=re.search(r'textureWidth\s*=\s*(\d+)',s)[1];height=re.search(r'textureHeight\s*=\s*(\d+)',s)[1]
 lines.append(f' return LayerDefinition.create(mesh,{width},{height}).bakeRoot();}}');report[model]=len(names)
lines.append('}')
(R/'src/main/java/com/foundations/calculator/client/LegacyModels.java').write_text('\n'.join(lines)+'\n');(R/'tools/legacy_model_report.json').write_text(json.dumps(report,indent=2));print(report)
