package com.foundations.calculator.client;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
/** Upstream Calculator Techne meshes, MIT copyright Ollie Lansdell. Generated by tools/import_legacy_models.py. */
public final class LegacyModels {
 public static ModelPart chamber(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Corner1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(6.0f,8.0f,-8.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Corner2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(-8.0f,8.0f,-8.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Corner3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(6.0f,8.0f,6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Corner4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(-8.0f,8.0f,6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,24.0f,-6.0f,1.570796f,0.0f,0.0f));
 root.addOrReplaceChild("Side2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(-8.0f,24.0f,-6.0f,1.570796f,0.0f,0.0f));
 root.addOrReplaceChild("Side3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,10.0f,-6.0f,1.570796f,0.0f,0.0f));
 root.addOrReplaceChild("Side4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(-8.0f,10.0f,-6.0f,1.570796f,0.0f,0.0f));
 root.addOrReplaceChild("Side5",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,8.0f,-8.0f,0.0f,0.0f,1.570796f));
 root.addOrReplaceChild("Side6",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,22.0f,-8.0f,0.0f,0.0f,1.570796f));
 root.addOrReplaceChild("Side7",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,22.0f,6.0f,0.0f,0.0f,1.570796f));
 root.addOrReplaceChild("Side8",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,2.0f),PartPose.offsetAndRotation(6.0f,8.0f,6.0f,0.0f,0.0f,1.570796f));
 root.addOrReplaceChild("Tray",CubeListBuilder.create().texOffs(0,19).addBox(0.0f,0.0f,0.0f,12.0f,1.0f,12.0f),PartPose.offsetAndRotation(-6.0f,19.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Screen",CubeListBuilder.create().texOffs(42,0).addBox(0.0f,0.0f,0.0f,10.0f,4.0f,1.0f),PartPose.offsetAndRotation(-5.0f,17.5f,-6.0f,-0.4363323f,0.0f,0.0f));
 root.addOrReplaceChild("Side9",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,12.0f),PartPose.offsetAndRotation(5.0f,20.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side10",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,12.0f),PartPose.offsetAndRotation(-7.0f,20.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side11",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,12.0f),PartPose.offsetAndRotation(-6.0f,20.0f,7.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Side12",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,12.0f),PartPose.offsetAndRotation(-6.0f,20.0f,-5.0f,0.0f,1.570796f,0.0f));
 return LayerDefinition.create(mesh,64,32).bakeRoot();}
 public static ModelPart processing(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Scanner1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,3.0f),PartPose.offsetAndRotation(-4.0f,15.0f,3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Scanner2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,3.0f),PartPose.offsetAndRotation(3.0f,15.0f,3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Scanner3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,7.0f,3.0f),PartPose.offsetAndRotation(3.5f,14.0f,3.0f,0.0f,0.0f,1.570796f));
 return LayerDefinition.create(mesh,64,32).bakeRoot();}
 public static ModelPart split(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Split1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(-0.5f,10.0f,-0.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Split2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,3.0f,1.0f,3.0f),PartPose.offsetAndRotation(-1.5f,13.0f,-1.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Frame1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,12.0f,1.0f,2.0f),PartPose.offsetAndRotation(-6.0f,9.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Frame2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,10.0f,2.0f),PartPose.offsetAndRotation(-7.0f,10.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Frame3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,10.0f,2.0f),PartPose.offsetAndRotation(6.0f,10.0f,-1.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,64,32).bakeRoot();}
 public static ModelPart conductorMast(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Centre_Piece",CubeListBuilder.create().texOffs(64,0).addBox(0.0f,0.0f,0.0f,4.0f,58.0f,4.0f),PartPose.offsetAndRotation(-2.0f,-36.0f,-2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod1",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(2.0f,-20.0f,1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod2",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(-4.0f,-20.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod3",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(2.0f,-20.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod4",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(-4.0f,-20.0f,1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod5",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(-1.0f,-20.0f,2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod6",CubeListBuilder.create().texOffs(0,80).addBox(0.0f,0.0f,0.0f,2.0f,42.0f,2.0f),PartPose.offsetAndRotation(-1.0f,-20.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Top1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(0.0f,-40.0f,0.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Top2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(-2.0f,-40.0f,1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Top3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(1.0f,-40.0f,-2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Top4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,2.0f,1.0f),PartPose.offsetAndRotation(-2.0f,-38.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Top5",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,2.0f,1.0f),PartPose.offsetAndRotation(1.0f,-38.0f,1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,8.0f,1.0f,8.0f),PartPose.offsetAndRotation(-4.0f,0.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,10.0f,1.0f,10.0f),PartPose.offsetAndRotation(-5.0f,22.0f,-5.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Bottom1",CubeListBuilder.create().texOffs(0,50).addBox(0.0f,0.0f,0.0f,16.0f,1.0f,16.0f),PartPose.offsetAndRotation(-8.0f,23.0f,-8.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod7",CubeListBuilder.create().texOffs(0,20).addBox(0.0f,0.0f,0.0f,1.0f,15.0f,1.0f),PartPose.offsetAndRotation(6.0f,8.0f,6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod8",CubeListBuilder.create().texOffs(0,20).addBox(0.0f,0.0f,0.0f,1.0f,15.0f,1.0f),PartPose.offsetAndRotation(6.0f,8.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod9",CubeListBuilder.create().texOffs(0,20).addBox(0.0f,0.0f,0.0f,1.0f,15.0f,1.0f),PartPose.offsetAndRotation(-7.0f,8.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Rod10",CubeListBuilder.create().texOffs(0,20).addBox(0.0f,0.0f,0.0f,1.0f,15.0f,1.0f),PartPose.offsetAndRotation(-7.0f,8.0f,6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,8.0f,1.0f,8.0f),PartPose.offsetAndRotation(-4.0f,-2.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,10.0f,1.0f,10.0f),PartPose.offsetAndRotation(-5.0f,-4.0f,-5.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre5",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,10.0f,1.0f,10.0f),PartPose.offsetAndRotation(-5.0f,-6.0f,-5.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre6",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,12.0f,1.0f,12.0f),PartPose.offsetAndRotation(-6.0f,-8.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre7",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,10.0f,1.0f,10.0f),PartPose.offsetAndRotation(-5.0f,-18.0f,-5.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre8",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,6.0f,4.0f,6.0f),PartPose.offsetAndRotation(-3.0f,-30.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre9",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,6.0f,1.0f,6.0f),PartPose.offsetAndRotation(-3.0f,-32.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Power2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,4.0f,5.0f,3.0f),PartPose.offsetAndRotation(-2.0f,17.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Power1",CubeListBuilder.create().texOffs(100,0).addBox(0.0f,0.0f,0.0f,6.0f,6.0f,1.0f),PartPose.offsetAndRotation(-3.0f,16.0f,-8.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,256,128).bakeRoot();}
 public static ModelPart transmitter(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Centre",CubeListBuilder.create().texOffs(0,36).addBox(0.0f,0.0f,0.0f,2.0f,26.0f,2.0f),PartPose.offsetAndRotation(-1.0f,-8.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Bar1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,20.0f,1.0f,1.0f),PartPose.offsetAndRotation(-10.0f,-4.0f,1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Bar2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,20.0f,1.0f,1.0f),PartPose.offsetAndRotation(-10.0f,-4.0f,-2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Bar3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,20.0f,1.0f,1.0f),PartPose.offsetAndRotation(1.0f,-4.0f,10.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Bar4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,20.0f,1.0f,1.0f),PartPose.offsetAndRotation(-2.0f,-4.0f,10.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Middle",CubeListBuilder.create().texOffs(0,11).addBox(0.0f,0.0f,0.0f,4.0f,9.0f,4.0f),PartPose.offsetAndRotation(-2.0f,1.0f,-2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Bottom",CubeListBuilder.create().texOffs(0,24).addBox(0.0f,0.0f,0.0f,6.0f,6.0f,6.0f),PartPose.offsetAndRotation(-3.0f,18.0f,-3.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,128,64).bakeRoot();}
 public static ModelPart scarecrow(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(72,0).addBox(0.0f,0.0f,0.0f,14.0f,1.0f,14.0f),PartPose.offsetAndRotation(-7.0f,23.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Support",CubeListBuilder.create().texOffs(60,0).addBox(0.0f,0.0f,0.0f,2.0f,24.0f,2.0f),PartPose.offsetAndRotation(-1.0f,-1.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Shoulders",CubeListBuilder.create().texOffs(68,15).addBox(0.0f,0.0f,0.0f,28.0f,2.0f,2.0f),PartPose.offsetAndRotation(-14.0f,2.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Head",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,12.0f,12.0f,12.0f),PartPose.offsetAndRotation(-6.0f,-13.0f,-6.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Hat1",CubeListBuilder.create().texOffs(72,33).addBox(0.0f,0.0f,0.0f,14.0f,2.0f,14.0f),PartPose.offsetAndRotation(-7.0f,-15.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Hat2",CubeListBuilder.create().texOffs(84,19).addBox(0.0f,0.0f,0.0f,11.0f,3.0f,11.0f),PartPose.offsetAndRotation(-5.5f,-18.0f,-5.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Shape1",CubeListBuilder.create().texOffs(128,0).addBox(0.0f,0.0f,0.0f,14.0f,16.0f,10.0f),PartPose.offsetAndRotation(-7.0f,1.0f,-5.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,256,128).bakeRoot();}
 public static ModelPart dockingStation(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,14.0f,1.0f,14.0f),PartPose.offsetAndRotation(-7.0f,23.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre",CubeListBuilder.create().texOffs(0,26).addBox(0.0f,0.0f,0.0f,2.0f,12.0f,1.0f),PartPose.offsetAndRotation(-1.0f,11.0f,0.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Support1",CubeListBuilder.create().texOffs(0,16).addBox(0.0f,0.0f,0.0f,4.0f,7.0f,1.0f),PartPose.offsetAndRotation(-2.0f,8.9f,2.0f,-0.7853982f,0.0f,0.0f));
 root.addOrReplaceChild("Support_2",CubeListBuilder.create().texOffs(0,24).addBox(0.0f,0.0f,0.0f,4.0f,1.0f,1.0f),PartPose.offsetAndRotation(-2.0f,13.0f,-3.5f,0.7853982f,0.0f,0.0f));
 root.addOrReplaceChild("Con2",CubeListBuilder.create().texOffs(0,52).addBox(0.0f,0.0f,0.0f,1.0f,6.0f,6.0f),PartPose.offsetAndRotation(-8.0f,13.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Con3",CubeListBuilder.create().texOffs(0,52).addBox(0.0f,0.0f,0.0f,1.0f,6.0f,6.0f),PartPose.offsetAndRotation(-3.0f,13.0f,-7.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Con4",CubeListBuilder.create().texOffs(0,52).addBox(0.0f,0.0f,0.0f,1.0f,6.0f,6.0f),PartPose.offsetAndRotation(-3.0f,13.0f,8.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Con5",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,14.0f),PartPose.offsetAndRotation(-1.0f,15.001f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Con6",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,2.0f,14.0f),PartPose.offsetAndRotation(-7.0f,15.001f,1.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Stem1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,4.0f,2.0f),PartPose.offsetAndRotation(-1.0f,18.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stem2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,4.0f,2.0f),PartPose.offsetAndRotation(-1.0f,18.0f,2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stem3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,4.0f,2.0f),PartPose.offsetAndRotation(3.0f,18.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stem4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,2.0f,4.0f,2.0f),PartPose.offsetAndRotation(-5.0f,18.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,6.0f,2.0f,6.0f),PartPose.offsetAndRotation(-3.0f,15.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Base2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,10.0f,1.0f,10.0f),PartPose.offsetAndRotation(-5.0f,22.0f,-5.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Centre2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,8.0f,1.0f,8.0f),PartPose.offsetAndRotation(-4.0f,17.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Con1",CubeListBuilder.create().texOffs(0,52).addBox(0.0f,0.0f,0.0f,1.0f,6.0f,6.0f),PartPose.offsetAndRotation(7.0f,13.0f,-3.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,128,64).bakeRoot();}
 public static ModelPart crankHandle(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("base",CubeListBuilder.create().texOffs(0,14).addBox(0.0f,0.0f,0.0f,2.0f,3.0f,2.0f),PartPose.offsetAndRotation(-1.0f,21.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("piece",CubeListBuilder.create().texOffs(0,8).addBox(0.0f,0.0f,0.0f,2.0f,4.0f,2.0f),PartPose.offsetAndRotation(3.0f,15.0f,-1.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("grasp",CubeListBuilder.create().texOffs(0,4).addBox(0.0f,0.0f,0.0f,3.0f,1.0f,3.0f),PartPose.offsetAndRotation(2.5f,14.0f,-1.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("joint",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,6.0f,2.0f,2.0f),PartPose.offsetAndRotation(-1.0f,19.0f,-1.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,64,32).bakeRoot();}
 public static ModelPart weatherStationBase(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(0,47).addBox(0.0f,0.0f,0.0f,16.0f,1.0f,16.0f),PartPose.offsetAndRotation(-8.0f,23.0f,-8.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand",CubeListBuilder.create().texOffs(0,23).addBox(0.0f,0.0f,0.0f,2.0f,20.0f,4.0f),PartPose.offsetAndRotation(1.0f,3.0f,-2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand2",CubeListBuilder.create().texOffs(0,16).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(1.0f,18.0f,2.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand3",CubeListBuilder.create().texOffs(0,16).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(1.0f,18.0f,-3.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,1.0f,6.0f,6.0f),PartPose.offsetAndRotation(0.0f,17.0f,-3.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,128,64).bakeRoot();}
 public static ModelPart weatherStationDish(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(0,36).addBox(0.0f,0.0f,0.0f,26.0f,2.0f,26.0f),PartPose.offsetAndRotation(-13.0f,22.0f,-13.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side1",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,28.0f,2.0f,2.0f),PartPose.offsetAndRotation(-14.0f,20.0f,12.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side2",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,28.0f,2.0f,2.0f),PartPose.offsetAndRotation(-14.0f,20.0f,-14.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side3",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,24.0f,2.0f,2.0f),PartPose.offsetAndRotation(12.0f,20.0f,12.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Side4",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,24.0f,2.0f,2.0f),PartPose.offsetAndRotation(-14.0f,20.0f,12.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Side5",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,32.0f,2.0f,2.0f),PartPose.offsetAndRotation(-16.0f,18.0f,13.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side6",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,32.0f,2.0f,2.0f),PartPose.offsetAndRotation(-16.0f,18.0f,-15.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Side7",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,26.0f,2.0f,2.0f),PartPose.offsetAndRotation(-16.0f,18.0f,13.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Side8",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,26.0f,2.0f,2.0f),PartPose.offsetAndRotation(14.0f,18.0f,13.0f,0.0f,1.570796f,0.0f));
 root.addOrReplaceChild("Support1",CubeListBuilder.create().texOffs(0,18).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(-2.0f,9.0f,-13.0f,0.0f,0.0f,-0.5235988f));
 root.addOrReplaceChild("Support2",CubeListBuilder.create().texOffs(0,18).addBox(0.0f,0.0f,0.0f,2.0f,16.0f,2.0f),PartPose.offsetAndRotation(0.0f,8.0f,-13.0f,0.0f,0.0f,0.5235988f));
 root.addOrReplaceChild("Beam",CubeListBuilder.create().texOffs(0,10).addBox(0.0f,0.0f,0.0f,4.0f,4.0f,4.0f),PartPose.offsetAndRotation(-2.0f,6.0f,-14.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Middle1",CubeListBuilder.create().texOffs(24,27).addBox(0.0f,0.0f,0.0f,8.0f,1.0f,8.0f),PartPose.offsetAndRotation(-4.0f,21.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Middle2",CubeListBuilder.create().texOffs(8,30).addBox(0.0f,0.0f,0.0f,4.0f,2.0f,4.0f),PartPose.offsetAndRotation(-2.0f,19.0f,-2.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,128,64).bakeRoot();}
 public static ModelPart fabricationArm(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Arm1",CubeListBuilder.create().texOffs(0,24).addBox(-1.0f,-0.5f,-6.0f,1.0f,1.0f,7.0f),PartPose.offsetAndRotation(-1.0f,22.0f,-0.5f,-0.7853982f,0.0f,0.0f));
 root.addOrReplaceChild("Arm2",CubeListBuilder.create().texOffs(0,24).addBox(0.0f,-0.5f,-6.0f,1.0f,1.0f,7.0f),PartPose.offsetAndRotation(1.0f,22.0f,-0.5f,-0.7853982f,0.0f,0.0f));
 root.addOrReplaceChild("Arm3",CubeListBuilder.create().texOffs(16,24).addBox(-1.0f,-0.5f,-6.0f,2.0f,1.0f,7.0f),PartPose.offsetAndRotation(0.0f,18.0f,-4.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Arm4",CubeListBuilder.create().texOffs(0,21).addBox(-1.0f,0.5f,-5.0f,2.0f,2.0f,1.0f),PartPose.offsetAndRotation(0.0f,18.0f,-4.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(6,20).addBox(-1.0f,-1.0f,-1.0f,2.0f,2.0f,2.0f),PartPose.offsetAndRotation(0.0f,23.0f,0.0f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,64,32).bakeRoot();}
 public static ModelPart magneticFlux(){MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
 root.addOrReplaceChild("Base",CubeListBuilder.create().texOffs(0,0).addBox(0.0f,0.0f,0.0f,16.0f,2.0f,16.0f),PartPose.offsetAndRotation(-8.0f,22.0f,-8.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Base2",CubeListBuilder.create().texOffs(0,18).addBox(0.0f,0.0f,0.0f,14.0f,1.0f,14.0f),PartPose.offsetAndRotation(-7.0f,21.0f,-7.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand1",CubeListBuilder.create().texOffs(0,33).addBox(0.0f,0.0f,0.0f,8.0f,1.0f,8.0f),PartPose.offsetAndRotation(-4.0f,18.0f,-4.0f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Stand2",CubeListBuilder.create().texOffs(32,33).addBox(0.0f,0.0f,0.0f,3.0f,2.0f,3.0f),PartPose.offsetAndRotation(-1.5f,19.0f,-1.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Magnet1",CubeListBuilder.create().texOffs(0,42).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(1.0f,12.0f,-0.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Magnet2",CubeListBuilder.create().texOffs(0,42).addBox(0.0f,0.0f,0.0f,1.0f,4.0f,1.0f),PartPose.offsetAndRotation(-2.0f,12.0f,-0.5f,0.0f,0.0f,0.0f));
 root.addOrReplaceChild("Magnet3",CubeListBuilder.create().texOffs(4,42).addBox(0.0f,0.0f,0.0f,4.0f,1.0f,1.0f),PartPose.offsetAndRotation(-2.0f,16.0f,-0.5f,0.0f,0.0f,0.0f));
 return LayerDefinition.create(mesh,128,64).bakeRoot();}
}
